// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPoolMetadataByPoolID = `-- name: GetPoolMetadataByPoolID :one
SELECT id, chain_id, pool_id, owner_address, name, description, theme_key, theme_id, metadata_cid, metadata_uri, metadata_gateway_url, cover_asset_id, ticket_art_asset_id, created_at, updated_at
FROM pool_metadata
WHERE chain_id = $1
  AND pool_id = $2
`

type GetPoolMetadataByPoolIDParams struct {
	ChainID int64 `json:"chain_id"`
	PoolID  int64 `json:"pool_id"`
}

func (q *Queries) GetPoolMetadataByPoolID(ctx context.Context, arg GetPoolMetadataByPoolIDParams) (PoolMetadatum, error) {
	row := q.db.QueryRow(ctx, getPoolMetadataByPoolID, arg.ChainID, arg.PoolID)
	var i PoolMetadatum
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.PoolID,
		&i.OwnerAddress,
		&i.Name,
		&i.Description,
		&i.ThemeKey,
		&i.ThemeID,
		&i.MetadataCid,
		&i.MetadataUri,
		&i.MetadataGatewayUrl,
		&i.CoverAssetID,
		&i.TicketArtAssetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoolMetadataDraft = `-- name: GetPoolMetadataDraft :one
SELECT id, chain_id, owner_address, name, description, theme_key, cover_asset_id, ticket_art_asset_id, metadata_cid, metadata_uri, metadata_gateway_url, theme_id, pool_config_preview, prize_tiers, status, expires_at, created_at, updated_at
FROM pool_metadata_drafts
WHERE chain_id = $1
  AND id = $2
`

type GetPoolMetadataDraftParams struct {
	ChainID int64 `json:"chain_id"`
	ID      int64 `json:"id"`
}

func (q *Queries) GetPoolMetadataDraft(ctx context.Context, arg GetPoolMetadataDraftParams) (PoolMetadataDraft, error) {
	row := q.db.QueryRow(ctx, getPoolMetadataDraft, arg.ChainID, arg.ID)
	var i PoolMetadataDraft
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.OwnerAddress,
		&i.Name,
		&i.Description,
		&i.ThemeKey,
		&i.CoverAssetID,
		&i.TicketArtAssetID,
		&i.MetadataCid,
		&i.MetadataUri,
		&i.MetadataGatewayUrl,
		&i.ThemeID,
		&i.PoolConfigPreview,
		&i.PrizeTiers,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadedAsset = `-- name: GetUploadedAsset :one
SELECT id, owner_address, kind, cid, ipfs_uri, gateway_url, mime_type, size_bytes, sha256, created_at
FROM uploaded_assets
WHERE id = $1
`

func (q *Queries) GetUploadedAsset(ctx context.Context, id int64) (UploadedAsset, error) {
	row := q.db.QueryRow(ctx, getUploadedAsset, id)
	var i UploadedAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerAddress,
		&i.Kind,
		&i.Cid,
		&i.IpfsUri,
		&i.GatewayUrl,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const insertPoolMetadataDraft = `-- name: InsertPoolMetadataDraft :one
INSERT INTO pool_metadata_drafts (
    chain_id,
    owner_address,
    name,
    description,
    theme_key,
    cover_asset_id,
    ticket_art_asset_id,
    metadata_cid,
    metadata_uri,
    metadata_gateway_url,
    theme_id,
    pool_config_preview,
    prize_tiers,
    status,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, chain_id, owner_address, name, description, theme_key, cover_asset_id, ticket_art_asset_id, metadata_cid, metadata_uri, metadata_gateway_url, theme_id, pool_config_preview, prize_tiers, status, expires_at, created_at, updated_at
`

type InsertPoolMetadataDraftParams struct {
	ChainID            int64              `json:"chain_id"`
	OwnerAddress       string             `json:"owner_address"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	ThemeKey           string             `json:"theme_key"`
	CoverAssetID       pgtype.Int8        `json:"cover_asset_id"`
	TicketArtAssetID   pgtype.Int8        `json:"ticket_art_asset_id"`
	MetadataCid        string             `json:"metadata_cid"`
	MetadataUri        string             `json:"metadata_uri"`
	MetadataGatewayUrl string             `json:"metadata_gateway_url"`
	ThemeID            string             `json:"theme_id"`
	PoolConfigPreview  []byte             `json:"pool_config_preview"`
	PrizeTiers         []byte             `json:"prize_tiers"`
	Status             string             `json:"status"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertPoolMetadataDraft(ctx context.Context, arg InsertPoolMetadataDraftParams) (PoolMetadataDraft, error) {
	row := q.db.QueryRow(ctx, insertPoolMetadataDraft,
		arg.ChainID,
		arg.OwnerAddress,
		arg.Name,
		arg.Description,
		arg.ThemeKey,
		arg.CoverAssetID,
		arg.TicketArtAssetID,
		arg.MetadataCid,
		arg.MetadataUri,
		arg.MetadataGatewayUrl,
		arg.ThemeID,
		arg.PoolConfigPreview,
		arg.PrizeTiers,
		arg.Status,
		arg.ExpiresAt,
	)
	var i PoolMetadataDraft
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.OwnerAddress,
		&i.Name,
		&i.Description,
		&i.ThemeKey,
		&i.CoverAssetID,
		&i.TicketArtAssetID,
		&i.MetadataCid,
		&i.MetadataUri,
		&i.MetadataGatewayUrl,
		&i.ThemeID,
		&i.PoolConfigPreview,
		&i.PrizeTiers,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUploadedAsset = `-- name: InsertUploadedAsset :one
INSERT INTO uploaded_assets (
    owner_address,
    kind,
    cid,
    ipfs_uri,
    gateway_url,
    mime_type,
    size_bytes,
    sha256
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, owner_address, kind, cid, ipfs_uri, gateway_url, mime_type, size_bytes, sha256, created_at
`

type InsertUploadedAssetParams struct {
	OwnerAddress string `json:"owner_address"`
	Kind         string `json:"kind"`
	Cid          string `json:"cid"`
	IpfsUri      string `json:"ipfs_uri"`
	GatewayUrl   string `json:"gateway_url"`
	MimeType     string `json:"mime_type"`
	SizeBytes    int64  `json:"size_bytes"`
	Sha256       string `json:"sha256"`
}

func (q *Queries) InsertUploadedAsset(ctx context.Context, arg InsertUploadedAssetParams) (UploadedAsset, error) {
	row := q.db.QueryRow(ctx, insertUploadedAsset,
		arg.OwnerAddress,
		arg.Kind,
		arg.Cid,
		arg.IpfsUri,
		arg.GatewayUrl,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i UploadedAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerAddress,
		&i.Kind,
		&i.Cid,
		&i.IpfsUri,
		&i.GatewayUrl,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const updatePoolMetadataDraftStatus = `-- name: UpdatePoolMetadataDraftStatus :one
UPDATE pool_metadata_drafts
SET status = $3,
    updated_at = NOW()
WHERE chain_id = $1
  AND id = $2
RETURNING id, chain_id, owner_address, name, description, theme_key, cover_asset_id, ticket_art_asset_id, metadata_cid, metadata_uri, metadata_gateway_url, theme_id, pool_config_preview, prize_tiers, status, expires_at, created_at, updated_at
`

type UpdatePoolMetadataDraftStatusParams struct {
	ChainID int64  `json:"chain_id"`
	ID      int64  `json:"id"`
	Status  string `json:"status"`
}

func (q *Queries) UpdatePoolMetadataDraftStatus(ctx context.Context, arg UpdatePoolMetadataDraftStatusParams) (PoolMetadataDraft, error) {
	row := q.db.QueryRow(ctx, updatePoolMetadataDraftStatus, arg.ChainID, arg.ID, arg.Status)
	var i PoolMetadataDraft
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.OwnerAddress,
		&i.Name,
		&i.Description,
		&i.ThemeKey,
		&i.CoverAssetID,
		&i.TicketArtAssetID,
		&i.MetadataCid,
		&i.MetadataUri,
		&i.MetadataGatewayUrl,
		&i.ThemeID,
		&i.PoolConfigPreview,
		&i.PrizeTiers,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPoolMetadata = `-- name: UpsertPoolMetadata :one
INSERT INTO pool_metadata (
    chain_id,
    pool_id,
    owner_address,
    name,
    description,
    theme_key,
    theme_id,
    metadata_cid,
    metadata_uri,
    metadata_gateway_url,
    cover_asset_id,
    ticket_art_asset_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (chain_id, pool_id) DO UPDATE SET
    owner_address = EXCLUDED.owner_address,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    theme_key = EXCLUDED.theme_key,
    theme_id = EXCLUDED.theme_id,
    metadata_cid = EXCLUDED.metadata_cid,
    metadata_uri = EXCLUDED.metadata_uri,
    metadata_gateway_url = EXCLUDED.metadata_gateway_url,
    cover_asset_id = EXCLUDED.cover_asset_id,
    ticket_art_asset_id = EXCLUDED.ticket_art_asset_id,
    updated_at = NOW()
RETURNING id, chain_id, pool_id, owner_address, name, description, theme_key, theme_id, metadata_cid, metadata_uri, metadata_gateway_url, cover_asset_id, ticket_art_asset_id, created_at, updated_at
`

type UpsertPoolMetadataParams struct {
	ChainID            int64       `json:"chain_id"`
	PoolID             int64       `json:"pool_id"`
	OwnerAddress       string      `json:"owner_address"`
	Name               string      `json:"name"`
	Description        string      `json:"description"`
	ThemeKey           string      `json:"theme_key"`
	ThemeID            string      `json:"theme_id"`
	MetadataCid        string      `json:"metadata_cid"`
	MetadataUri        string      `json:"metadata_uri"`
	MetadataGatewayUrl string      `json:"metadata_gateway_url"`
	CoverAssetID       pgtype.Int8 `json:"cover_asset_id"`
	TicketArtAssetID   pgtype.Int8 `json:"ticket_art_asset_id"`
}

func (q *Queries) UpsertPoolMetadata(ctx context.Context, arg UpsertPoolMetadataParams) (PoolMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertPoolMetadata,
		arg.ChainID,
		arg.PoolID,
		arg.OwnerAddress,
		arg.Name,
		arg.Description,
		arg.ThemeKey,
		arg.ThemeID,
		arg.MetadataCid,
		arg.MetadataUri,
		arg.MetadataGatewayUrl,
		arg.CoverAssetID,
		arg.TicketArtAssetID,
	)
	var i PoolMetadatum
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.PoolID,
		&i.OwnerAddress,
		&i.Name,
		&i.Description,
		&i.ThemeKey,
		&i.ThemeID,
		&i.MetadataCid,
		&i.MetadataUri,
		&i.MetadataGatewayUrl,
		&i.CoverAssetID,
		&i.TicketArtAssetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
