// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: costs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGlobalCostTotal = `-- name: GetGlobalCostTotal :one
SELECT COALESCE(SUM(amount), 0)::BIGINT
FROM pool_cost_ledgers
WHERE chain_id = $1
`

func (q *Queries) GetGlobalCostTotal(ctx context.Context, chainID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getGlobalCostTotal, chainID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getGlobalSponsorCostTotal = `-- name: GetGlobalSponsorCostTotal :one
SELECT COALESCE(SUM(amount), 0)::BIGINT
FROM pool_cost_ledgers
WHERE chain_id = $1
  AND cost_type = 'SPONSOR_GAS'
`

func (q *Queries) GetGlobalSponsorCostTotal(ctx context.Context, chainID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getGlobalSponsorCostTotal, chainID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPoolCostTotal = `-- name: GetPoolCostTotal :one
SELECT COALESCE(SUM(amount), 0)::BIGINT
FROM pool_cost_ledgers
WHERE chain_id = $1
  AND pool_id = $2
`

type GetPoolCostTotalParams struct {
	ChainID int64 `json:"chain_id"`
	PoolID  int64 `json:"pool_id"`
}

func (q *Queries) GetPoolCostTotal(ctx context.Context, arg GetPoolCostTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPoolCostTotal, arg.ChainID, arg.PoolID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPoolCostTotals = `-- name: GetPoolCostTotals :many
SELECT
    cost_type,
    COALESCE(SUM(amount), 0)::BIGINT AS total_amount
FROM pool_cost_ledgers
WHERE chain_id = $1
  AND pool_id = $2
GROUP BY cost_type
ORDER BY cost_type ASC
`

type GetPoolCostTotalsParams struct {
	ChainID int64 `json:"chain_id"`
	PoolID  int64 `json:"pool_id"`
}

type GetPoolCostTotalsRow struct {
	CostType    string `json:"cost_type"`
	TotalAmount int64  `json:"total_amount"`
}

func (q *Queries) GetPoolCostTotals(ctx context.Context, arg GetPoolCostTotalsParams) ([]GetPoolCostTotalsRow, error) {
	rows, err := q.db.Query(ctx, getPoolCostTotals, arg.ChainID, arg.PoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPoolCostTotalsRow{}
	for rows.Next() {
		var i GetPoolCostTotalsRow
		if err := rows.Scan(&i.CostType, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPoolSponsorCostTotal = `-- name: GetPoolSponsorCostTotal :one
SELECT COALESCE(SUM(amount), 0)::BIGINT
FROM pool_cost_ledgers
WHERE chain_id = $1
  AND pool_id = $2
  AND cost_type = 'SPONSOR_GAS'
`

type GetPoolSponsorCostTotalParams struct {
	ChainID int64 `json:"chain_id"`
	PoolID  int64 `json:"pool_id"`
}

func (q *Queries) GetPoolSponsorCostTotal(ctx context.Context, arg GetPoolSponsorCostTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPoolSponsorCostTotal, arg.ChainID, arg.PoolID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertPoolCostLedger = `-- name: InsertPoolCostLedger :one
INSERT INTO pool_cost_ledgers (
    chain_id,
    pool_id,
    round_id,
    cost_type,
    amount,
    tx_hash,
    ref_type,
    ref_id,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (chain_id, cost_type, ref_type, ref_id) DO UPDATE SET
    round_id = EXCLUDED.round_id,
    amount = EXCLUDED.amount,
    tx_hash = EXCLUDED.tx_hash,
    metadata = EXCLUDED.metadata
RETURNING id, chain_id, pool_id, round_id, cost_type, amount, tx_hash, ref_type, ref_id, metadata, created_at
`

type InsertPoolCostLedgerParams struct {
	ChainID  int64       `json:"chain_id"`
	PoolID   int64       `json:"pool_id"`
	RoundID  pgtype.Int8 `json:"round_id"`
	CostType string      `json:"cost_type"`
	Amount   int64       `json:"amount"`
	TxHash   string      `json:"tx_hash"`
	RefType  string      `json:"ref_type"`
	RefID    string      `json:"ref_id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) InsertPoolCostLedger(ctx context.Context, arg InsertPoolCostLedgerParams) (PoolCostLedger, error) {
	row := q.db.QueryRow(ctx, insertPoolCostLedger,
		arg.ChainID,
		arg.PoolID,
		arg.RoundID,
		arg.CostType,
		arg.Amount,
		arg.TxHash,
		arg.RefType,
		arg.RefID,
		arg.Metadata,
	)
	var i PoolCostLedger
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.PoolID,
		&i.RoundID,
		&i.CostType,
		&i.Amount,
		&i.TxHash,
		&i.RefType,
		&i.RefID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listPoolCostLedgers = `-- name: ListPoolCostLedgers :many
SELECT id, chain_id, pool_id, round_id, cost_type, amount, tx_hash, ref_type, ref_id, metadata, created_at
FROM pool_cost_ledgers
WHERE chain_id = $1
  AND pool_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListPoolCostLedgersParams struct {
	ChainID int64 `json:"chain_id"`
	PoolID  int64 `json:"pool_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPoolCostLedgers(ctx context.Context, arg ListPoolCostLedgersParams) ([]PoolCostLedger, error) {
	rows, err := q.db.Query(ctx, listPoolCostLedgers,
		arg.ChainID,
		arg.PoolID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoolCostLedger{}
	for rows.Next() {
		var i PoolCostLedger
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.PoolID,
			&i.RoundID,
			&i.CostType,
			&i.Amount,
			&i.TxHash,
			&i.RefType,
			&i.RefID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
