// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: indexer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIndexedLogsFromBlock = `-- name: DeleteIndexedLogsFromBlock :exec
DELETE FROM indexed_logs
WHERE chain_id = $1
  AND contract_name = $2
  AND block_number >= $3
`

type DeleteIndexedLogsFromBlockParams struct {
	ChainID      int64  `json:"chain_id"`
	ContractName string `json:"contract_name"`
	BlockNumber  int64  `json:"block_number"`
}

func (q *Queries) DeleteIndexedLogsFromBlock(ctx context.Context, arg DeleteIndexedLogsFromBlockParams) error {
	_, err := q.db.Exec(ctx, deleteIndexedLogsFromBlock, arg.ChainID, arg.ContractName, arg.BlockNumber)
	return err
}

const getIndexerCursor = `-- name: GetIndexerCursor :one
SELECT chain_id, contract_name, last_processed_block, last_processed_log_index, updated_at
FROM indexer_cursors
WHERE chain_id = $1
  AND contract_name = $2
`

type GetIndexerCursorParams struct {
	ChainID      int64  `json:"chain_id"`
	ContractName string `json:"contract_name"`
}

func (q *Queries) GetIndexerCursor(ctx context.Context, arg GetIndexerCursorParams) (IndexerCursor, error) {
	row := q.db.QueryRow(ctx, getIndexerCursor, arg.ChainID, arg.ContractName)
	var i IndexerCursor
	err := row.Scan(
		&i.ChainID,
		&i.ContractName,
		&i.LastProcessedBlock,
		&i.LastProcessedLogIndex,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIndexedLog = `-- name: InsertIndexedLog :one
INSERT INTO indexed_logs (
    chain_id,
    contract_name,
    contract_address,
    event_name,
    tx_hash,
    log_index,
    block_number,
    block_hash,
    event_key,
    removed,
    pool_id,
    round_id,
    ticket_id,
    user_address,
    digest,
    payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (chain_id, tx_hash, log_index) DO UPDATE SET
    contract_name = EXCLUDED.contract_name,
    contract_address = EXCLUDED.contract_address,
    event_name = EXCLUDED.event_name,
    block_number = EXCLUDED.block_number,
    block_hash = EXCLUDED.block_hash,
    event_key = EXCLUDED.event_key,
    removed = EXCLUDED.removed,
    pool_id = EXCLUDED.pool_id,
    round_id = EXCLUDED.round_id,
    ticket_id = EXCLUDED.ticket_id,
    user_address = EXCLUDED.user_address,
    digest = EXCLUDED.digest,
    payload = EXCLUDED.payload
RETURNING id, chain_id, contract_name, contract_address, event_name, tx_hash, log_index, block_number, block_hash, event_key, removed, pool_id, round_id, ticket_id, user_address, digest, payload, created_at
`

type InsertIndexedLogParams struct {
	ChainID         int64       `json:"chain_id"`
	ContractName    string      `json:"contract_name"`
	ContractAddress string      `json:"contract_address"`
	EventName       string      `json:"event_name"`
	TxHash          string      `json:"tx_hash"`
	LogIndex        int64       `json:"log_index"`
	BlockNumber     int64       `json:"block_number"`
	BlockHash       string      `json:"block_hash"`
	EventKey        string      `json:"event_key"`
	Removed         bool        `json:"removed"`
	PoolID          pgtype.Int8 `json:"pool_id"`
	RoundID         pgtype.Int8 `json:"round_id"`
	TicketID        pgtype.Int8 `json:"ticket_id"`
	UserAddress     string      `json:"user_address"`
	Digest          string      `json:"digest"`
	Payload         []byte      `json:"payload"`
}

func (q *Queries) InsertIndexedLog(ctx context.Context, arg InsertIndexedLogParams) (IndexedLog, error) {
	row := q.db.QueryRow(ctx, insertIndexedLog,
		arg.ChainID,
		arg.ContractName,
		arg.ContractAddress,
		arg.EventName,
		arg.TxHash,
		arg.LogIndex,
		arg.BlockNumber,
		arg.BlockHash,
		arg.EventKey,
		arg.Removed,
		arg.PoolID,
		arg.RoundID,
		arg.TicketID,
		arg.UserAddress,
		arg.Digest,
		arg.Payload,
	)
	var i IndexedLog
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.ContractName,
		&i.ContractAddress,
		&i.EventName,
		&i.TxHash,
		&i.LogIndex,
		&i.BlockNumber,
		&i.BlockHash,
		&i.EventKey,
		&i.Removed,
		&i.PoolID,
		&i.RoundID,
		&i.TicketID,
		&i.UserAddress,
		&i.Digest,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listIndexedLogsFromBlock = `-- name: ListIndexedLogsFromBlock :many
SELECT id, chain_id, contract_name, contract_address, event_name, tx_hash, log_index, block_number, block_hash, event_key, removed, pool_id, round_id, ticket_id, user_address, digest, payload, created_at
FROM indexed_logs
WHERE chain_id = $1
  AND contract_name = $2
  AND block_number >= $3
ORDER BY block_number ASC, log_index ASC
`

type ListIndexedLogsFromBlockParams struct {
	ChainID      int64  `json:"chain_id"`
	ContractName string `json:"contract_name"`
	BlockNumber  int64  `json:"block_number"`
}

func (q *Queries) ListIndexedLogsFromBlock(ctx context.Context, arg ListIndexedLogsFromBlockParams) ([]IndexedLog, error) {
	rows, err := q.db.Query(ctx, listIndexedLogsFromBlock, arg.ChainID, arg.ContractName, arg.BlockNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IndexedLog{}
	for rows.Next() {
		var i IndexedLog
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.ContractName,
			&i.ContractAddress,
			&i.EventName,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.BlockHash,
			&i.EventKey,
			&i.Removed,
			&i.PoolID,
			&i.RoundID,
			&i.TicketID,
			&i.UserAddress,
			&i.Digest,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIndexerCursor = `-- name: UpsertIndexerCursor :one
INSERT INTO indexer_cursors (
    chain_id,
    contract_name,
    last_processed_block,
    last_processed_log_index
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (chain_id, contract_name) DO UPDATE SET
    last_processed_block = EXCLUDED.last_processed_block,
    last_processed_log_index = EXCLUDED.last_processed_log_index,
    updated_at = NOW()
RETURNING chain_id, contract_name, last_processed_block, last_processed_log_index, updated_at
`

type UpsertIndexerCursorParams struct {
	ChainID               int64  `json:"chain_id"`
	ContractName          string `json:"contract_name"`
	LastProcessedBlock    int64  `json:"last_processed_block"`
	LastProcessedLogIndex int64  `json:"last_processed_log_index"`
}

func (q *Queries) UpsertIndexerCursor(ctx context.Context, arg UpsertIndexerCursorParams) (IndexerCursor, error) {
	row := q.db.QueryRow(ctx, upsertIndexerCursor,
		arg.ChainID,
		arg.ContractName,
		arg.LastProcessedBlock,
		arg.LastProcessedLogIndex,
	)
	var i IndexerCursor
	err := row.Scan(
		&i.ChainID,
		&i.ContractName,
		&i.LastProcessedBlock,
		&i.LastProcessedLogIndex,
		&i.UpdatedAt,
	)
	return i, err
}
