// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: leaderboards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformOverview = `-- name: GetPlatformOverview :one
SELECT
  COALESCE((SELECT COUNT(*)::BIGINT FROM pools WHERE pools.chain_id = $1), 0::BIGINT) AS total_pools,
  COALESCE((SELECT COUNT(*)::BIGINT FROM pools WHERE pools.chain_id = $1 AND pools.status != 'Closed'), 0::BIGINT) AS active_pools,
  COALESCE((SELECT SUM(pools.realized_revenue)::BIGINT FROM pools WHERE pools.chain_id = $1), 0::BIGINT) AS total_realized_revenue,
  COALESCE((SELECT COUNT(*)::BIGINT FROM tickets WHERE tickets.chain_id = $1 AND tickets.status IN ('Scratched', 'Claimed')), 0::BIGINT) AS total_revealed_tickets,
  COALESCE((SELECT COUNT(*)::BIGINT FROM tickets WHERE tickets.chain_id = $1 AND lower(tickets.claimed_by) != '' AND tickets.claim_clear_reward_amount > 0), 0::BIGINT) AS total_winning_claims,
  COALESCE((SELECT SUM(tickets.claim_clear_reward_amount)::BIGINT FROM tickets WHERE tickets.chain_id = $1 AND lower(tickets.claimed_by) != '' AND tickets.claim_clear_reward_amount > 0), 0::BIGINT) AS total_claimed_rewards
`

type GetPlatformOverviewRow struct {
	TotalPools           interface{} `json:"total_pools"`
	ActivePools          interface{} `json:"active_pools"`
	TotalRealizedRevenue interface{} `json:"total_realized_revenue"`
	TotalRevealedTickets interface{} `json:"total_revealed_tickets"`
	TotalWinningClaims   interface{} `json:"total_winning_claims"`
	TotalClaimedRewards  interface{} `json:"total_claimed_rewards"`
}

func (q *Queries) GetPlatformOverview(ctx context.Context, chainID int64) (GetPlatformOverviewRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOverview, chainID)
	var i GetPlatformOverviewRow
	err := row.Scan(
		&i.TotalPools,
		&i.ActivePools,
		&i.TotalRealizedRevenue,
		&i.TotalRevealedTickets,
		&i.TotalWinningClaims,
		&i.TotalClaimedRewards,
	)
	return i, err
}

const listRecentWins = `-- name: ListRecentWins :many
SELECT id, chain_id, ticket_id, pool_id, round_id, owner, ticket_index, status, reveal_authorized, transferred_before_scratch, mint_tx_hash, claimed_by, claim_clear_reward_amount, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
FROM tickets
WHERE chain_id = $1
  AND lower(claimed_by) != ''
  AND claim_clear_reward_amount > 0
ORDER BY updated_at DESC, ticket_id DESC
LIMIT $2 OFFSET $3
`

type ListRecentWinsParams struct {
	ChainID int64 `json:"chain_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListRecentWins(ctx context.Context, arg ListRecentWinsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listRecentWins, arg.ChainID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.TicketID,
			&i.PoolID,
			&i.RoundID,
			&i.Owner,
			&i.TicketIndex,
			&i.Status,
			&i.RevealAuthorized,
			&i.TransferredBeforeScratch,
			&i.MintTxHash,
			&i.ClaimedBy,
			&i.ClaimClearRewardAmount,
			&i.LastEventBlock,
			&i.LastEventTxHash,
			&i.LastEventLogIndex,
			&i.LastEventBlockHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopPlayersAllTime = `-- name: ListTopPlayersAllTime :many
SELECT
  lower(t.claimed_by) AS player_address,
  MIN(t.claimed_by)::TEXT AS display_address,
  COUNT(*)::BIGINT AS win_count,
  COALESCE(SUM(t.claim_clear_reward_amount), 0)::BIGINT AS total_reward_amount,
  MAX(t.updated_at)::TIMESTAMPTZ AS last_win_at,
  COALESCE(us.nickname, '') AS nickname,
  COALESCE(us.avatar_url, '') AS avatar_url
FROM tickets t
LEFT JOIN user_settings us ON us.wallet_address = lower(t.claimed_by)
WHERE t.chain_id = $1
  AND lower(t.claimed_by) != ''
  AND t.claim_clear_reward_amount > 0
GROUP BY lower(t.claimed_by), us.nickname, us.avatar_url
ORDER BY total_reward_amount DESC, win_count DESC, last_win_at DESC
LIMIT $2
`

type ListTopPlayersAllTimeParams struct {
	ChainID int64 `json:"chain_id"`
	Limit   int32 `json:"limit"`
}

type ListTopPlayersAllTimeRow struct {
	PlayerAddress     string             `json:"player_address"`
	DisplayAddress    string             `json:"display_address"`
	WinCount          int64              `json:"win_count"`
	TotalRewardAmount int64              `json:"total_reward_amount"`
	LastWinAt         pgtype.Timestamptz `json:"last_win_at"`
	Nickname          string             `json:"nickname"`
	AvatarUrl         string             `json:"avatar_url"`
}

func (q *Queries) ListTopPlayersAllTime(ctx context.Context, arg ListTopPlayersAllTimeParams) ([]ListTopPlayersAllTimeRow, error) {
	rows, err := q.db.Query(ctx, listTopPlayersAllTime, arg.ChainID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopPlayersAllTimeRow{}
	for rows.Next() {
		var i ListTopPlayersAllTimeRow
		if err := rows.Scan(
			&i.PlayerAddress,
			&i.DisplayAddress,
			&i.WinCount,
			&i.TotalRewardAmount,
			&i.LastWinAt,
			&i.Nickname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopPlayersSince = `-- name: ListTopPlayersSince :many
SELECT
  lower(t.claimed_by) AS player_address,
  MIN(t.claimed_by)::TEXT AS display_address,
  COUNT(*)::BIGINT AS win_count,
  COALESCE(SUM(t.claim_clear_reward_amount), 0)::BIGINT AS total_reward_amount,
  MAX(t.updated_at)::TIMESTAMPTZ AS last_win_at,
  COALESCE(us.nickname, '') AS nickname,
  COALESCE(us.avatar_url, '') AS avatar_url
FROM tickets t
LEFT JOIN user_settings us ON us.wallet_address = lower(t.claimed_by)
WHERE t.chain_id = $1
  AND lower(t.claimed_by) != ''
  AND t.claim_clear_reward_amount > 0
  AND t.updated_at >= $2
GROUP BY lower(t.claimed_by), us.nickname, us.avatar_url
ORDER BY total_reward_amount DESC, win_count DESC, last_win_at DESC
LIMIT $3
`

type ListTopPlayersSinceParams struct {
	ChainID   int64              `json:"chain_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

type ListTopPlayersSinceRow struct {
	PlayerAddress     string             `json:"player_address"`
	DisplayAddress    string             `json:"display_address"`
	WinCount          int64              `json:"win_count"`
	TotalRewardAmount int64              `json:"total_reward_amount"`
	LastWinAt         pgtype.Timestamptz `json:"last_win_at"`
	Nickname          string             `json:"nickname"`
	AvatarUrl         string             `json:"avatar_url"`
}

func (q *Queries) ListTopPlayersSince(ctx context.Context, arg ListTopPlayersSinceParams) ([]ListTopPlayersSinceRow, error) {
	rows, err := q.db.Query(ctx, listTopPlayersSince, arg.ChainID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopPlayersSinceRow{}
	for rows.Next() {
		var i ListTopPlayersSinceRow
		if err := rows.Scan(
			&i.PlayerAddress,
			&i.DisplayAddress,
			&i.WinCount,
			&i.TotalRewardAmount,
			&i.LastWinAt,
			&i.Nickname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
