// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         int64              `json:"id"`
	Actor      string             `json:"actor"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type DeploymentRegistry struct {
	ID                int64              `json:"id"`
	ChainID           int64              `json:"chain_id"`
	ChainName         string             `json:"chain_name"`
	ContractName      string             `json:"contract_name"`
	ContractAddress   string             `json:"contract_address"`
	DeploymentBlock   int64              `json:"deployment_block"`
	DeploymentTxHash  string             `json:"deployment_tx_hash"`
	DeploymentVersion string             `json:"deployment_version"`
	AbiSourcePath     string             `json:"abi_source_path"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type GaslessControl struct {
	ID          int64              `json:"id"`
	ScopeType   string             `json:"scope_type"`
	ScopeKey    string             `json:"scope_key"`
	ControlType string             `json:"control_type"`
	IsActive    bool               `json:"is_active"`
	Reason      string             `json:"reason"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GaslessRequest struct {
	ID                   int64              `json:"id"`
	ChainID              int64              `json:"chain_id"`
	Digest               string             `json:"digest"`
	UserAddress          string             `json:"user_address"`
	Action               string             `json:"action"`
	TargetContract       string             `json:"target_contract"`
	ParamsHash           string             `json:"params_hash"`
	Nonce                int64              `json:"nonce"`
	Deadline             int64              `json:"deadline"`
	Status               string             `json:"status"`
	FailureCode          string             `json:"failure_code"`
	FailureReason        string             `json:"failure_reason"`
	TxHash               string             `json:"tx_hash"`
	GasUsed              pgtype.Int8        `json:"gas_used"`
	EffectiveGasPriceWei pgtype.Int8        `json:"effective_gas_price_wei"`
	GasCostWei           pgtype.Int8        `json:"gas_cost_wei"`
	PoolID               pgtype.Int8        `json:"pool_id"`
	RoundID              pgtype.Int8        `json:"round_id"`
	TicketID             pgtype.Int8        `json:"ticket_id"`
	RequestPayload       []byte             `json:"request_payload"`
	Signature            string             `json:"signature"`
	ReceiptBlockNumber   pgtype.Int8        `json:"receipt_block_number"`
	ReceiptBlockHash     string             `json:"receipt_block_hash"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	ConfirmedAt          pgtype.Timestamptz `json:"confirmed_at"`
	FinalizedAt          pgtype.Timestamptz `json:"finalized_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type IndexedLog struct {
	ID              int64              `json:"id"`
	ChainID         int64              `json:"chain_id"`
	ContractName    string             `json:"contract_name"`
	ContractAddress string             `json:"contract_address"`
	EventName       string             `json:"event_name"`
	TxHash          string             `json:"tx_hash"`
	LogIndex        int64              `json:"log_index"`
	BlockNumber     int64              `json:"block_number"`
	BlockHash       string             `json:"block_hash"`
	EventKey        string             `json:"event_key"`
	Removed         bool               `json:"removed"`
	PoolID          pgtype.Int8        `json:"pool_id"`
	RoundID         pgtype.Int8        `json:"round_id"`
	TicketID        pgtype.Int8        `json:"ticket_id"`
	UserAddress     string             `json:"user_address"`
	Digest          string             `json:"digest"`
	Payload         []byte             `json:"payload"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type IndexerCursor struct {
	ChainID               int64              `json:"chain_id"`
	ContractName          string             `json:"contract_name"`
	LastProcessedBlock    int64              `json:"last_processed_block"`
	LastProcessedLogIndex int64              `json:"last_processed_log_index"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID                      int64              `json:"id"`
	JobKey                  string             `json:"job_key"`
	JobType                 string             `json:"job_type"`
	Payload                 []byte             `json:"payload"`
	Status                  string             `json:"status"`
	ScheduleIntervalSeconds int32              `json:"schedule_interval_seconds"`
	RunAfter                pgtype.Timestamptz `json:"run_after"`
	LastStartedAt           pgtype.Timestamptz `json:"last_started_at"`
	LastFinishedAt          pgtype.Timestamptz `json:"last_finished_at"`
	LockedAt                pgtype.Timestamptz `json:"locked_at"`
	LockedBy                string             `json:"locked_by"`
	Attempts                int32              `json:"attempts"`
	MaxAttempts             int32              `json:"max_attempts"`
	LastError               string             `json:"last_error"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Pool struct {
	ID                     int64              `json:"id"`
	ChainID                int64              `json:"chain_id"`
	PoolID                 int64              `json:"pool_id"`
	Creator                string             `json:"creator"`
	ProtocolOwned          bool               `json:"protocol_owned"`
	Mode                   string             `json:"mode"`
	Status                 string             `json:"status"`
	Paused                 bool               `json:"paused"`
	CloseRequested         bool               `json:"close_requested"`
	VrfPending             bool               `json:"vrf_pending"`
	Initialized            bool               `json:"initialized"`
	ThemeID                string             `json:"theme_id"`
	TicketPrice            int64              `json:"ticket_price"`
	TotalTicketsPerRound   int64              `json:"total_tickets_per_round"`
	TotalPrizeBudget       int64              `json:"total_prize_budget"`
	PoolInstanceGroupSize  int64              `json:"pool_instance_group_size"`
	FeeBps                 int32              `json:"fee_bps"`
	TargetRtpBps           int32              `json:"target_rtp_bps"`
	HitRateBps             int32              `json:"hit_rate_bps"`
	MaxPrize               int64              `json:"max_prize"`
	Selectable             bool               `json:"selectable"`
	CurrentRound           int64              `json:"current_round"`
	LockedBond             int64              `json:"locked_bond"`
	ReservedPrizeBudget    int64              `json:"reserved_prize_budget"`
	LockedNextRoundBudget  int64              `json:"locked_next_round_budget"`
	RealizedRevenue        int64              `json:"realized_revenue"`
	SettledPrizeCost       int64              `json:"settled_prize_cost"`
	SettledProtocolCost    int64              `json:"settled_protocol_cost"`
	AccruedPlatformFee     int64              `json:"accrued_platform_fee"`
	CreatorProfitClaimed   int64              `json:"creator_profit_claimed"`
	ClaimableCreatorProfit int64              `json:"claimable_creator_profit"`
	CreatedBlock           int64              `json:"created_block"`
	CreatedTxHash          string             `json:"created_tx_hash"`
	LastEventBlock         int64              `json:"last_event_block"`
	LastEventTxHash        string             `json:"last_event_tx_hash"`
	LastEventLogIndex      int64              `json:"last_event_log_index"`
	LastEventBlockHash     string             `json:"last_event_block_hash"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type PoolCostLedger struct {
	ID        int64              `json:"id"`
	ChainID   int64              `json:"chain_id"`
	PoolID    int64              `json:"pool_id"`
	RoundID   pgtype.Int8        `json:"round_id"`
	CostType  string             `json:"cost_type"`
	Amount    int64              `json:"amount"`
	TxHash    string             `json:"tx_hash"`
	RefType   string             `json:"ref_type"`
	RefID     string             `json:"ref_id"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RevealRequest struct {
	ID                       int64              `json:"id"`
	ChainID                  int64              `json:"chain_id"`
	TicketID                 int64              `json:"ticket_id"`
	RequestUser              string             `json:"request_user"`
	OwnerSnapshot            string             `json:"owner_snapshot"`
	RequestStatus            string             `json:"request_status"`
	ZamaRequestRef           string             `json:"zama_request_ref"`
	TicketStatusSnapshot     string             `json:"ticket_status_snapshot"`
	RevealAuthorizedSnapshot bool               `json:"reveal_authorized_snapshot"`
	AuthPayload              []byte             `json:"auth_payload"`
	ClaimClearRewardAmount   pgtype.Int8        `json:"claim_clear_reward_amount"`
	ClaimProofRef            string             `json:"claim_proof_ref"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type Round struct {
	ID                   int64              `json:"id"`
	ChainID              int64              `json:"chain_id"`
	PoolID               int64              `json:"pool_id"`
	RoundID              int64              `json:"round_id"`
	Status               string             `json:"status"`
	SoldCount            int64              `json:"sold_count"`
	ScratchedCount       int64              `json:"scratched_count"`
	ClaimedCount         int64              `json:"claimed_count"`
	WinClaimableCount    int64              `json:"win_claimable_count"`
	TotalTickets         int64              `json:"total_tickets"`
	TicketPrice          int64              `json:"ticket_price"`
	RoundPrizeBudget     int64              `json:"round_prize_budget"`
	VrfRequestRef        string             `json:"vrf_request_ref"`
	ShuffleRoot          string             `json:"shuffle_root"`
	LastVrfRequestedAt   pgtype.Timestamptz `json:"last_vrf_requested_at"`
	LastVrfInitializedAt pgtype.Timestamptz `json:"last_vrf_initialized_at"`
	LastEventBlock       int64              `json:"last_event_block"`
	LastEventTxHash      string             `json:"last_event_tx_hash"`
	LastEventLogIndex    int64              `json:"last_event_log_index"`
	LastEventBlockHash   string             `json:"last_event_block_hash"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Ticket struct {
	ID                       int64              `json:"id"`
	ChainID                  int64              `json:"chain_id"`
	TicketID                 int64              `json:"ticket_id"`
	PoolID                   int64              `json:"pool_id"`
	RoundID                  int64              `json:"round_id"`
	Owner                    string             `json:"owner"`
	TicketIndex              int64              `json:"ticket_index"`
	Status                   string             `json:"status"`
	RevealAuthorized         bool               `json:"reveal_authorized"`
	TransferredBeforeScratch bool               `json:"transferred_before_scratch"`
	MintTxHash               string             `json:"mint_tx_hash"`
	ClaimedBy                string             `json:"claimed_by"`
	ClaimClearRewardAmount   int64              `json:"claim_clear_reward_amount"`
	LastEventBlock           int64              `json:"last_event_block"`
	LastEventTxHash          string             `json:"last_event_tx_hash"`
	LastEventLogIndex        int64              `json:"last_event_log_index"`
	LastEventBlockHash       string             `json:"last_event_block_hash"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            int64              `json:"id"`
	WalletAddress string             `json:"wallet_address"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
}
