// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimDueJobs(ctx context.Context, arg ClaimDueJobsParams) ([]Job, error)
	CountTicketsByOwnerFiltered(ctx context.Context, arg CountTicketsByOwnerFilteredParams) (int64, error)
	DeleteIndexedLogsFromBlock(ctx context.Context, arg DeleteIndexedLogsFromBlockParams) error
	DeletePool(ctx context.Context, arg DeletePoolParams) error
	DeleteRound(ctx context.Context, arg DeleteRoundParams) error
	DeleteTicket(ctx context.Context, arg DeleteTicketParams) error
	GetActiveDeployment(ctx context.Context, arg GetActiveDeploymentParams) (DeploymentRegistry, error)
	GetGlobalCostTotal(ctx context.Context, chainID int64) (int64, error)
	GetIndexerCursor(ctx context.Context, arg GetIndexerCursorParams) (IndexerCursor, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	GetLatestRevealRequest(ctx context.Context, arg GetLatestRevealRequestParams) (RevealRequest, error)
	GetPlatformOverview(ctx context.Context, chainID int64) (GetPlatformOverviewRow, error)
	GetPool(ctx context.Context, arg GetPoolParams) (Pool, error)
	GetPoolCostTotal(ctx context.Context, arg GetPoolCostTotalParams) (int64, error)
	GetPoolCostTotals(ctx context.Context, arg GetPoolCostTotalsParams) ([]GetPoolCostTotalsRow, error)
	GetPoolMetadataByPoolID(ctx context.Context, arg GetPoolMetadataByPoolIDParams) (PoolMetadatum, error)
	GetPoolMetadataDraft(ctx context.Context, arg GetPoolMetadataDraftParams) (PoolMetadataDraft, error)
	GetRevealRequestByJobRef(ctx context.Context, arg GetRevealRequestByJobRefParams) (RevealRequest, error)
	GetRevealRequestByZamaRequestRef(ctx context.Context, arg GetRevealRequestByZamaRequestRefParams) (RevealRequest, error)
	GetRound(ctx context.Context, arg GetRoundParams) (Round, error)
	GetTicket(ctx context.Context, arg GetTicketParams) (Ticket, error)
	GetUploadedAsset(ctx context.Context, id int64) (UploadedAsset, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertIndexedLog(ctx context.Context, arg InsertIndexedLogParams) (IndexedLog, error)
	InsertPoolCostLedger(ctx context.Context, arg InsertPoolCostLedgerParams) (PoolCostLedger, error)
	InsertPoolMetadataDraft(ctx context.Context, arg InsertPoolMetadataDraftParams) (PoolMetadataDraft, error)
	InsertRevealRequest(ctx context.Context, arg InsertRevealRequestParams) (RevealRequest, error)
	InsertUploadedAsset(ctx context.Context, arg InsertUploadedAssetParams) (UploadedAsset, error)
	ListActiveDeployments(ctx context.Context, chainID int64) ([]DeploymentRegistry, error)
	ListAllPoolsByCreator(ctx context.Context, arg ListAllPoolsByCreatorParams) ([]Pool, error)
	ListIndexedLogsFromBlock(ctx context.Context, arg ListIndexedLogsFromBlockParams) ([]IndexedLog, error)
	ListIndexerCursors(ctx context.Context, chainID int64) ([]IndexerCursor, error)
	ListJobs(ctx context.Context) ([]Job, error)
	ListPoolCostLedgers(ctx context.Context, arg ListPoolCostLedgersParams) ([]PoolCostLedger, error)
	ListPools(ctx context.Context, arg ListPoolsParams) ([]Pool, error)
	ListPoolsByCreator(ctx context.Context, arg ListPoolsByCreatorParams) ([]Pool, error)
	ListRecentWins(ctx context.Context, arg ListRecentWinsParams) ([]Ticket, error)
	ListStaleSubmittingRevealRequests(ctx context.Context, arg ListStaleSubmittingRevealRequestsParams) ([]RevealRequest, error)
	ListSubmittedRevealRequests(ctx context.Context, arg ListSubmittedRevealRequestsParams) ([]RevealRequest, error)
	ListTicketIDsByPoolAndRoundFromIndexedLogs(ctx context.Context, arg ListTicketIDsByPoolAndRoundFromIndexedLogsParams) ([]pgtype.Int8, error)
	ListTicketIDsByPoolFromIndexedLogs(ctx context.Context, arg ListTicketIDsByPoolFromIndexedLogsParams) ([]pgtype.Int8, error)
	ListTicketsByOwner(ctx context.Context, arg ListTicketsByOwnerParams) ([]Ticket, error)
	ListTicketsByOwnerFiltered(ctx context.Context, arg ListTicketsByOwnerFilteredParams) ([]Ticket, error)
	ListTicketsByPool(ctx context.Context, arg ListTicketsByPoolParams) ([]Ticket, error)
	ListTicketsByPoolAndRound(ctx context.Context, arg ListTicketsByPoolAndRoundParams) ([]Ticket, error)
	ListTopPlayersAllTime(ctx context.Context, arg ListTopPlayersAllTimeParams) ([]ListTopPlayersAllTimeRow, error)
	ListTopPlayersSince(ctx context.Context, arg ListTopPlayersSinceParams) ([]ListTopPlayersSinceRow, error)
	ListWinsByUser(ctx context.Context, arg ListWinsByUserParams) ([]Ticket, error)
	MarkJobCompleted(ctx context.Context, arg MarkJobCompletedParams) (Job, error)
	MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (Job, error)
	ReleaseStaleRunningJobs(ctx context.Context, dollar_1 int64) ([]Job, error)
	RetryJob(ctx context.Context, id int64) (Job, error)
	UpdatePoolMetadataDraftStatus(ctx context.Context, arg UpdatePoolMetadataDraftStatusParams) (PoolMetadataDraft, error)
	UpdateRevealRequestProxyState(ctx context.Context, arg UpdateRevealRequestProxyStateParams) (RevealRequest, error)
	UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) (DeploymentRegistry, error)
	UpsertIndexerCursor(ctx context.Context, arg UpsertIndexerCursorParams) (IndexerCursor, error)
	UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error)
	UpsertPool(ctx context.Context, arg UpsertPoolParams) (Pool, error)
	UpsertPoolMetadata(ctx context.Context, arg UpsertPoolMetadataParams) (PoolMetadatum, error)
	UpsertRound(ctx context.Context, arg UpsertRoundParams) (Round, error)
	UpsertTicket(ctx context.Context, arg UpsertTicketParams) (Ticket, error)
	UpsertUser(ctx context.Context, walletAddress string) (User, error)
}

var _ Querier = (*Queries)(nil)
