// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: risk.sql

package db

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (
    actor,
    action,
    target_type,
    target_id,
    payload
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, actor, action, target_type, target_id, payload, created_at
`

type InsertAuditLogParams struct {
	Actor      string `json:"actor"`
	Action     string `json:"action"`
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	Payload    []byte `json:"payload"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
