// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: usersettings.sql

package db

import (
	"context"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT id, wallet_address, nickname, broadcast_wins, security_alerts, terminal_hints, auto_lock, created_at, updated_at FROM user_settings
WHERE wallet_address = lower($1)
`

func (q *Queries) GetUserSettings(ctx context.Context, walletAddress string) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, walletAddress)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.Nickname,
		&i.BroadcastWins,
		&i.SecurityAlerts,
		&i.TerminalHints,
		&i.AutoLock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
INSERT INTO user_settings (
    wallet_address,
    nickname,
    broadcast_wins,
    security_alerts,
    terminal_hints,
    auto_lock
) VALUES (
    lower($1),
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (wallet_address) DO UPDATE SET
    nickname = EXCLUDED.nickname,
    broadcast_wins = EXCLUDED.broadcast_wins,
    security_alerts = EXCLUDED.security_alerts,
    terminal_hints = EXCLUDED.terminal_hints,
    auto_lock = EXCLUDED.auto_lock,
    updated_at = NOW()
RETURNING id, wallet_address, nickname, broadcast_wins, security_alerts, terminal_hints, auto_lock, created_at, updated_at
`

type UpsertUserSettingsParams struct {
	WalletAddress  string `json:"wallet_address"`
	Nickname       string `json:"nickname"`
	BroadcastWins  bool   `json:"broadcast_wins"`
	SecurityAlerts bool   `json:"security_alerts"`
	TerminalHints  bool   `json:"terminal_hints"`
	AutoLock       bool   `json:"auto_lock"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, upsertUserSettings,
		arg.WalletAddress,
		arg.Nickname,
		arg.BroadcastWins,
		arg.SecurityAlerts,
		arg.TerminalHints,
		arg.AutoLock,
	)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.Nickname,
		&i.BroadcastWins,
		&i.SecurityAlerts,
		&i.TerminalHints,
		&i.AutoLock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
