// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: deployments.sql

package db

import (
	"context"
)

const getActiveDeployment = `-- name: GetActiveDeployment :one
SELECT id, chain_id, chain_name, contract_name, contract_address, deployment_block, deployment_tx_hash, deployment_version, abi_source_path, is_active, created_at, updated_at
FROM deployment_registry
WHERE chain_id = $1
  AND contract_name = $2
  AND is_active = TRUE
ORDER BY deployment_block DESC
LIMIT 1
`

type GetActiveDeploymentParams struct {
	ChainID      int64  `json:"chain_id"`
	ContractName string `json:"contract_name"`
}

func (q *Queries) GetActiveDeployment(ctx context.Context, arg GetActiveDeploymentParams) (DeploymentRegistry, error) {
	row := q.db.QueryRow(ctx, getActiveDeployment, arg.ChainID, arg.ContractName)
	var i DeploymentRegistry
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.ChainName,
		&i.ContractName,
		&i.ContractAddress,
		&i.DeploymentBlock,
		&i.DeploymentTxHash,
		&i.DeploymentVersion,
		&i.AbiSourcePath,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDeployments = `-- name: ListActiveDeployments :many
SELECT id, chain_id, chain_name, contract_name, contract_address, deployment_block, deployment_tx_hash, deployment_version, abi_source_path, is_active, created_at, updated_at
FROM deployment_registry
WHERE chain_id = $1
  AND is_active = TRUE
ORDER BY contract_name ASC, deployment_block DESC
`

func (q *Queries) ListActiveDeployments(ctx context.Context, chainID int64) ([]DeploymentRegistry, error) {
	rows, err := q.db.Query(ctx, listActiveDeployments, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentRegistry{}
	for rows.Next() {
		var i DeploymentRegistry
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.ChainName,
			&i.ContractName,
			&i.ContractAddress,
			&i.DeploymentBlock,
			&i.DeploymentTxHash,
			&i.DeploymentVersion,
			&i.AbiSourcePath,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeployment = `-- name: UpsertDeployment :one
INSERT INTO deployment_registry (
    chain_id,
    chain_name,
    contract_name,
    contract_address,
    deployment_block,
    deployment_tx_hash,
    deployment_version,
    abi_source_path,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (chain_id, contract_name, contract_address) DO UPDATE SET
    chain_name = EXCLUDED.chain_name,
    deployment_block = EXCLUDED.deployment_block,
    deployment_tx_hash = EXCLUDED.deployment_tx_hash,
    deployment_version = EXCLUDED.deployment_version,
    abi_source_path = EXCLUDED.abi_source_path,
    is_active = EXCLUDED.is_active,
    updated_at = NOW()
RETURNING id, chain_id, chain_name, contract_name, contract_address, deployment_block, deployment_tx_hash, deployment_version, abi_source_path, is_active, created_at, updated_at
`

type UpsertDeploymentParams struct {
	ChainID           int64  `json:"chain_id"`
	ChainName         string `json:"chain_name"`
	ContractName      string `json:"contract_name"`
	ContractAddress   string `json:"contract_address"`
	DeploymentBlock   int64  `json:"deployment_block"`
	DeploymentTxHash  string `json:"deployment_tx_hash"`
	DeploymentVersion string `json:"deployment_version"`
	AbiSourcePath     string `json:"abi_source_path"`
	IsActive          bool   `json:"is_active"`
}

func (q *Queries) UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) (DeploymentRegistry, error) {
	row := q.db.QueryRow(ctx, upsertDeployment,
		arg.ChainID,
		arg.ChainName,
		arg.ContractName,
		arg.ContractAddress,
		arg.DeploymentBlock,
		arg.DeploymentTxHash,
		arg.DeploymentVersion,
		arg.AbiSourcePath,
		arg.IsActive,
	)
	var i DeploymentRegistry
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.ChainName,
		&i.ContractName,
		&i.ContractAddress,
		&i.DeploymentBlock,
		&i.DeploymentTxHash,
		&i.DeploymentVersion,
		&i.AbiSourcePath,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
