// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: gasless.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillGaslessRequestOnchainState = `-- name: BackfillGaslessRequestOnchainState :one
UPDATE gasless_requests
SET status = $2,
    failure_code = $3,
    failure_reason = $4,
    tx_hash = CASE
        WHEN tx_hash = '' THEN $5
        ELSE tx_hash
    END,
    gas_used = COALESCE($6, gas_used),
    effective_gas_price_wei = COALESCE($7, effective_gas_price_wei),
    gas_cost_wei = COALESCE($8, gas_cost_wei),
    receipt_block_number = COALESCE($9, receipt_block_number),
    receipt_block_hash = CASE
        WHEN $10::text <> '' THEN $10::text
        ELSE receipt_block_hash
    END,
    submitted_at = CASE
        WHEN submitted_at IS NULL AND $5 <> '' THEN NOW()
        ELSE submitted_at
    END,
    confirmed_at = CASE
        WHEN $2 = 'confirmed' AND confirmed_at IS NULL THEN NOW()
        ELSE confirmed_at
    END,
    finalized_at = CASE
        WHEN $2 = 'finalized' AND finalized_at IS NULL THEN NOW()
        ELSE finalized_at
    END,
    updated_at = NOW()
WHERE digest = $1
RETURNING id, chain_id, digest, user_address, action, target_contract, params_hash, nonce, deadline, status, failure_code, failure_reason, tx_hash, gas_used, effective_gas_price_wei, gas_cost_wei, pool_id, round_id, ticket_id, request_payload, signature, receipt_block_number, receipt_block_hash, submitted_at, confirmed_at, finalized_at, created_at, updated_at
`

type BackfillGaslessRequestOnchainStateParams struct {
	Digest               string      `json:"digest"`
	Status               string      `json:"status"`
	FailureCode          string      `json:"failure_code"`
	FailureReason        string      `json:"failure_reason"`
	TxHash               string      `json:"tx_hash"`
	GasUsed              pgtype.Int8 `json:"gas_used"`
	EffectiveGasPriceWei pgtype.Int8 `json:"effective_gas_price_wei"`
	GasCostWei           pgtype.Int8 `json:"gas_cost_wei"`
	ReceiptBlockNumber   pgtype.Int8 `json:"receipt_block_number"`
	ReceiptBlockHash     string      `json:"receipt_block_hash"`
}

func (q *Queries) BackfillGaslessRequestOnchainState(ctx context.Context, arg BackfillGaslessRequestOnchainStateParams) (GaslessRequest, error) {
	row := q.db.QueryRow(ctx, backfillGaslessRequestOnchainState,
		arg.Digest,
		arg.Status,
		arg.FailureCode,
		arg.FailureReason,
		arg.TxHash,
		arg.GasUsed,
		arg.EffectiveGasPriceWei,
		arg.GasCostWei,
		arg.ReceiptBlockNumber,
		arg.ReceiptBlockHash,
	)
	var i GaslessRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Digest,
		&i.UserAddress,
		&i.Action,
		&i.TargetContract,
		&i.ParamsHash,
		&i.Nonce,
		&i.Deadline,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.TxHash,
		&i.GasUsed,
		&i.EffectiveGasPriceWei,
		&i.GasCostWei,
		&i.PoolID,
		&i.RoundID,
		&i.TicketID,
		&i.RequestPayload,
		&i.Signature,
		&i.ReceiptBlockNumber,
		&i.ReceiptBlockHash,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countRecentGaslessRequestsByUser = `-- name: CountRecentGaslessRequestsByUser :one
SELECT COUNT(*)::BIGINT
FROM gasless_requests
WHERE chain_id = $1
  AND lower(user_address) = lower($2)
  AND created_at >= $3
`

type CountRecentGaslessRequestsByUserParams struct {
	ChainID   int64              `json:"chain_id"`
	Lower     string             `json:"lower"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountRecentGaslessRequestsByUser(ctx context.Context, arg CountRecentGaslessRequestsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentGaslessRequestsByUser, arg.ChainID, arg.Lower, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getGaslessRequestByDigest = `-- name: GetGaslessRequestByDigest :one
SELECT id, chain_id, digest, user_address, action, target_contract, params_hash, nonce, deadline, status, failure_code, failure_reason, tx_hash, gas_used, effective_gas_price_wei, gas_cost_wei, pool_id, round_id, ticket_id, request_payload, signature, receipt_block_number, receipt_block_hash, submitted_at, confirmed_at, finalized_at, created_at, updated_at
FROM gasless_requests
WHERE digest = $1
`

func (q *Queries) GetGaslessRequestByDigest(ctx context.Context, digest string) (GaslessRequest, error) {
	row := q.db.QueryRow(ctx, getGaslessRequestByDigest, digest)
	var i GaslessRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Digest,
		&i.UserAddress,
		&i.Action,
		&i.TargetContract,
		&i.ParamsHash,
		&i.Nonce,
		&i.Deadline,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.TxHash,
		&i.GasUsed,
		&i.EffectiveGasPriceWei,
		&i.GasCostWei,
		&i.PoolID,
		&i.RoundID,
		&i.TicketID,
		&i.RequestPayload,
		&i.Signature,
		&i.ReceiptBlockNumber,
		&i.ReceiptBlockHash,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGaslessRequest = `-- name: InsertGaslessRequest :one
INSERT INTO gasless_requests (
    chain_id,
    digest,
    user_address,
    action,
    target_contract,
    params_hash,
    nonce,
    deadline,
    status,
    pool_id,
    round_id,
    ticket_id,
    request_payload,
    signature
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (digest) DO UPDATE SET
    user_address = EXCLUDED.user_address,
    action = EXCLUDED.action,
    target_contract = EXCLUDED.target_contract,
    params_hash = EXCLUDED.params_hash,
    nonce = EXCLUDED.nonce,
    deadline = EXCLUDED.deadline,
    pool_id = EXCLUDED.pool_id,
    round_id = EXCLUDED.round_id,
    ticket_id = EXCLUDED.ticket_id,
    request_payload = EXCLUDED.request_payload,
    signature = EXCLUDED.signature,
    updated_at = NOW()
RETURNING id, chain_id, digest, user_address, action, target_contract, params_hash, nonce, deadline, status, failure_code, failure_reason, tx_hash, gas_used, effective_gas_price_wei, gas_cost_wei, pool_id, round_id, ticket_id, request_payload, signature, receipt_block_number, receipt_block_hash, submitted_at, confirmed_at, finalized_at, created_at, updated_at
`

type InsertGaslessRequestParams struct {
	ChainID        int64       `json:"chain_id"`
	Digest         string      `json:"digest"`
	UserAddress    string      `json:"user_address"`
	Action         string      `json:"action"`
	TargetContract string      `json:"target_contract"`
	ParamsHash     string      `json:"params_hash"`
	Nonce          int64       `json:"nonce"`
	Deadline       int64       `json:"deadline"`
	Status         string      `json:"status"`
	PoolID         pgtype.Int8 `json:"pool_id"`
	RoundID        pgtype.Int8 `json:"round_id"`
	TicketID       pgtype.Int8 `json:"ticket_id"`
	RequestPayload []byte      `json:"request_payload"`
	Signature      string      `json:"signature"`
}

func (q *Queries) InsertGaslessRequest(ctx context.Context, arg InsertGaslessRequestParams) (GaslessRequest, error) {
	row := q.db.QueryRow(ctx, insertGaslessRequest,
		arg.ChainID,
		arg.Digest,
		arg.UserAddress,
		arg.Action,
		arg.TargetContract,
		arg.ParamsHash,
		arg.Nonce,
		arg.Deadline,
		arg.Status,
		arg.PoolID,
		arg.RoundID,
		arg.TicketID,
		arg.RequestPayload,
		arg.Signature,
	)
	var i GaslessRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Digest,
		&i.UserAddress,
		&i.Action,
		&i.TargetContract,
		&i.ParamsHash,
		&i.Nonce,
		&i.Deadline,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.TxHash,
		&i.GasUsed,
		&i.EffectiveGasPriceWei,
		&i.GasCostWei,
		&i.PoolID,
		&i.RoundID,
		&i.TicketID,
		&i.RequestPayload,
		&i.Signature,
		&i.ReceiptBlockNumber,
		&i.ReceiptBlockHash,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGaslessRequestsByStatuses = `-- name: ListGaslessRequestsByStatuses :many
SELECT id, chain_id, digest, user_address, action, target_contract, params_hash, nonce, deadline, status, failure_code, failure_reason, tx_hash, gas_used, effective_gas_price_wei, gas_cost_wei, pool_id, round_id, ticket_id, request_payload, signature, receipt_block_number, receipt_block_hash, submitted_at, confirmed_at, finalized_at, created_at, updated_at
FROM gasless_requests
WHERE chain_id = $1
  AND status = ANY($2::text[])
ORDER BY created_at ASC
LIMIT $3
`

type ListGaslessRequestsByStatusesParams struct {
	ChainID int64    `json:"chain_id"`
	Column2 []string `json:"column_2"`
	Limit   int32    `json:"limit"`
}

func (q *Queries) ListGaslessRequestsByStatuses(ctx context.Context, arg ListGaslessRequestsByStatusesParams) ([]GaslessRequest, error) {
	rows, err := q.db.Query(ctx, listGaslessRequestsByStatuses, arg.ChainID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GaslessRequest{}
	for rows.Next() {
		var i GaslessRequest
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.Digest,
			&i.UserAddress,
			&i.Action,
			&i.TargetContract,
			&i.ParamsHash,
			&i.Nonce,
			&i.Deadline,
			&i.Status,
			&i.FailureCode,
			&i.FailureReason,
			&i.TxHash,
			&i.GasUsed,
			&i.EffectiveGasPriceWei,
			&i.GasCostWei,
			&i.PoolID,
			&i.RoundID,
			&i.TicketID,
			&i.RequestPayload,
			&i.Signature,
			&i.ReceiptBlockNumber,
			&i.ReceiptBlockHash,
			&i.SubmittedAt,
			&i.ConfirmedAt,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGaslessRequestResult = `-- name: MarkGaslessRequestResult :one
UPDATE gasless_requests
SET status = $2,
    failure_code = $3,
    failure_reason = $4,
    gas_used = $5,
    effective_gas_price_wei = $6,
    gas_cost_wei = $7,
    receipt_block_number = $8,
    receipt_block_hash = $9,
    confirmed_at = CASE
        WHEN $2 = 'confirmed' THEN NOW()
        ELSE confirmed_at
    END,
    finalized_at = CASE
        WHEN $2 = 'finalized' THEN NOW()
        ELSE finalized_at
    END,
    updated_at = NOW()
WHERE digest = $1
RETURNING id, chain_id, digest, user_address, action, target_contract, params_hash, nonce, deadline, status, failure_code, failure_reason, tx_hash, gas_used, effective_gas_price_wei, gas_cost_wei, pool_id, round_id, ticket_id, request_payload, signature, receipt_block_number, receipt_block_hash, submitted_at, confirmed_at, finalized_at, created_at, updated_at
`

type MarkGaslessRequestResultParams struct {
	Digest               string      `json:"digest"`
	Status               string      `json:"status"`
	FailureCode          string      `json:"failure_code"`
	FailureReason        string      `json:"failure_reason"`
	GasUsed              pgtype.Int8 `json:"gas_used"`
	EffectiveGasPriceWei pgtype.Int8 `json:"effective_gas_price_wei"`
	GasCostWei           pgtype.Int8 `json:"gas_cost_wei"`
	ReceiptBlockNumber   pgtype.Int8 `json:"receipt_block_number"`
	ReceiptBlockHash     string      `json:"receipt_block_hash"`
}

func (q *Queries) MarkGaslessRequestResult(ctx context.Context, arg MarkGaslessRequestResultParams) (GaslessRequest, error) {
	row := q.db.QueryRow(ctx, markGaslessRequestResult,
		arg.Digest,
		arg.Status,
		arg.FailureCode,
		arg.FailureReason,
		arg.GasUsed,
		arg.EffectiveGasPriceWei,
		arg.GasCostWei,
		arg.ReceiptBlockNumber,
		arg.ReceiptBlockHash,
	)
	var i GaslessRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Digest,
		&i.UserAddress,
		&i.Action,
		&i.TargetContract,
		&i.ParamsHash,
		&i.Nonce,
		&i.Deadline,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.TxHash,
		&i.GasUsed,
		&i.EffectiveGasPriceWei,
		&i.GasCostWei,
		&i.PoolID,
		&i.RoundID,
		&i.TicketID,
		&i.RequestPayload,
		&i.Signature,
		&i.ReceiptBlockNumber,
		&i.ReceiptBlockHash,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markGaslessRequestSubmitted = `-- name: MarkGaslessRequestSubmitted :one
UPDATE gasless_requests
SET status = 'submitted',
    tx_hash = $2,
    submitted_at = NOW(),
    updated_at = NOW()
WHERE digest = $1
RETURNING id, chain_id, digest, user_address, action, target_contract, params_hash, nonce, deadline, status, failure_code, failure_reason, tx_hash, gas_used, effective_gas_price_wei, gas_cost_wei, pool_id, round_id, ticket_id, request_payload, signature, receipt_block_number, receipt_block_hash, submitted_at, confirmed_at, finalized_at, created_at, updated_at
`

type MarkGaslessRequestSubmittedParams struct {
	Digest string `json:"digest"`
	TxHash string `json:"tx_hash"`
}

func (q *Queries) MarkGaslessRequestSubmitted(ctx context.Context, arg MarkGaslessRequestSubmittedParams) (GaslessRequest, error) {
	row := q.db.QueryRow(ctx, markGaslessRequestSubmitted, arg.Digest, arg.TxHash)
	var i GaslessRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Digest,
		&i.UserAddress,
		&i.Action,
		&i.TargetContract,
		&i.ParamsHash,
		&i.Nonce,
		&i.Deadline,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.TxHash,
		&i.GasUsed,
		&i.EffectiveGasPriceWei,
		&i.GasCostWei,
		&i.PoolID,
		&i.RoundID,
		&i.TicketID,
		&i.RequestPayload,
		&i.Signature,
		&i.ReceiptBlockNumber,
		&i.ReceiptBlockHash,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markGaslessRequestValidated = `-- name: MarkGaslessRequestValidated :one
UPDATE gasless_requests
SET status = 'validated',
    updated_at = NOW()
WHERE digest = $1
RETURNING id, chain_id, digest, user_address, action, target_contract, params_hash, nonce, deadline, status, failure_code, failure_reason, tx_hash, gas_used, effective_gas_price_wei, gas_cost_wei, pool_id, round_id, ticket_id, request_payload, signature, receipt_block_number, receipt_block_hash, submitted_at, confirmed_at, finalized_at, created_at, updated_at
`

func (q *Queries) MarkGaslessRequestValidated(ctx context.Context, digest string) (GaslessRequest, error) {
	row := q.db.QueryRow(ctx, markGaslessRequestValidated, digest)
	var i GaslessRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Digest,
		&i.UserAddress,
		&i.Action,
		&i.TargetContract,
		&i.ParamsHash,
		&i.Nonce,
		&i.Deadline,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.TxHash,
		&i.GasUsed,
		&i.EffectiveGasPriceWei,
		&i.GasCostWei,
		&i.PoolID,
		&i.RoundID,
		&i.TicketID,
		&i.RequestPayload,
		&i.Signature,
		&i.ReceiptBlockNumber,
		&i.ReceiptBlockHash,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
