// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueJobs = `-- name: ClaimDueJobs :many
WITH picked AS (
    SELECT id
    FROM jobs
    WHERE status IN ('pending', 'completed', 'failed')
      AND run_after <= NOW()
    ORDER BY run_after ASC
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE jobs
SET status = 'running',
    locked_at = NOW(),
    locked_by = $2,
    last_started_at = NOW(),
    attempts = attempts + 1,
    updated_at = NOW()
WHERE id IN (SELECT id FROM picked)
RETURNING id, job_key, job_type, payload, status, schedule_interval_seconds, run_after, last_started_at, last_finished_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
`

type ClaimDueJobsParams struct {
	Limit    int32  `json:"limit"`
	LockedBy string `json:"locked_by"`
}

func (q *Queries) ClaimDueJobs(ctx context.Context, arg ClaimDueJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, claimDueJobs, arg.Limit, arg.LockedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.JobType,
			&i.Payload,
			&i.Status,
			&i.ScheduleIntervalSeconds,
			&i.RunAfter,
			&i.LastStartedAt,
			&i.LastFinishedAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT id, job_key, job_type, payload, status, schedule_interval_seconds, run_after, last_started_at, last_finished_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.ScheduleIntervalSeconds,
		&i.RunAfter,
		&i.LastStartedAt,
		&i.LastFinishedAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, job_key, job_type, payload, status, schedule_interval_seconds, run_after, last_started_at, last_finished_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
FROM jobs
ORDER BY job_key ASC
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.JobType,
			&i.Payload,
			&i.Status,
			&i.ScheduleIntervalSeconds,
			&i.RunAfter,
			&i.LastStartedAt,
			&i.LastFinishedAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobCompleted = `-- name: MarkJobCompleted :one
UPDATE jobs
SET status = 'completed',
    run_after = $2,
    locked_at = NULL,
    locked_by = '',
    last_finished_at = NOW(),
    last_error = '',
    updated_at = NOW()
WHERE id = $1
RETURNING id, job_key, job_type, payload, status, schedule_interval_seconds, run_after, last_started_at, last_finished_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
`

type MarkJobCompletedParams struct {
	ID       int64              `json:"id"`
	RunAfter pgtype.Timestamptz `json:"run_after"`
}

func (q *Queries) MarkJobCompleted(ctx context.Context, arg MarkJobCompletedParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobCompleted, arg.ID, arg.RunAfter)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.ScheduleIntervalSeconds,
		&i.RunAfter,
		&i.LastStartedAt,
		&i.LastFinishedAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markJobFailed = `-- name: MarkJobFailed :one
UPDATE jobs
SET status = 'failed',
    run_after = $2,
    locked_at = NULL,
    locked_by = '',
    last_finished_at = NOW(),
    last_error = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, job_key, job_type, payload, status, schedule_interval_seconds, run_after, last_started_at, last_finished_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
`

type MarkJobFailedParams struct {
	ID        int64              `json:"id"`
	RunAfter  pgtype.Timestamptz `json:"run_after"`
	LastError string             `json:"last_error"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobFailed, arg.ID, arg.RunAfter, arg.LastError)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.ScheduleIntervalSeconds,
		&i.RunAfter,
		&i.LastStartedAt,
		&i.LastFinishedAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseStaleRunningJobs = `-- name: ReleaseStaleRunningJobs :many
UPDATE jobs
SET status = 'pending',
    run_after = NOW(),
    locked_at = NULL,
    locked_by = '',
    last_error = CASE
        WHEN last_error = '' THEN 'job lock timed out and was reclaimed'
        ELSE last_error
    END,
    updated_at = NOW()
WHERE status = 'running'
  AND locked_at IS NOT NULL
  AND locked_at <= NOW() - ($1::BIGINT * INTERVAL '1 second')
RETURNING id, job_key, job_type, payload, status, schedule_interval_seconds, run_after, last_started_at, last_finished_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
`

func (q *Queries) ReleaseStaleRunningJobs(ctx context.Context, dollar_1 int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, releaseStaleRunningJobs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.JobType,
			&i.Payload,
			&i.Status,
			&i.ScheduleIntervalSeconds,
			&i.RunAfter,
			&i.LastStartedAt,
			&i.LastFinishedAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :one
UPDATE jobs
SET status = 'pending',
    run_after = NOW(),
    locked_at = NULL,
    locked_by = '',
    last_error = '',
    updated_at = NOW()
WHERE id = $1
RETURNING id, job_key, job_type, payload, status, schedule_interval_seconds, run_after, last_started_at, last_finished_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
`

func (q *Queries) RetryJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, retryJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.ScheduleIntervalSeconds,
		&i.RunAfter,
		&i.LastStartedAt,
		&i.LastFinishedAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertJob = `-- name: UpsertJob :one
INSERT INTO jobs (
    job_key,
    job_type,
    payload,
    status,
    schedule_interval_seconds,
    run_after,
    max_attempts
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (job_key) DO UPDATE SET
    job_type = EXCLUDED.job_type,
    payload = EXCLUDED.payload,
    schedule_interval_seconds = EXCLUDED.schedule_interval_seconds,
    max_attempts = EXCLUDED.max_attempts,
    updated_at = NOW()
RETURNING id, job_key, job_type, payload, status, schedule_interval_seconds, run_after, last_started_at, last_finished_at, locked_at, locked_by, attempts, max_attempts, last_error, created_at, updated_at
`

type UpsertJobParams struct {
	JobKey                  string             `json:"job_key"`
	JobType                 string             `json:"job_type"`
	Payload                 []byte             `json:"payload"`
	Status                  string             `json:"status"`
	ScheduleIntervalSeconds int32              `json:"schedule_interval_seconds"`
	RunAfter                pgtype.Timestamptz `json:"run_after"`
	MaxAttempts             int32              `json:"max_attempts"`
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.JobKey,
		arg.JobType,
		arg.Payload,
		arg.Status,
		arg.ScheduleIntervalSeconds,
		arg.RunAfter,
		arg.MaxAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.ScheduleIntervalSeconds,
		&i.RunAfter,
		&i.LastStartedAt,
		&i.LastFinishedAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
