// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pools.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePool = `-- name: DeletePool :exec
DELETE FROM pools
WHERE chain_id = $1
  AND pool_id = $2
`

type DeletePoolParams struct {
	ChainID int64 `json:"chain_id"`
	PoolID  int64 `json:"pool_id"`
}

func (q *Queries) DeletePool(ctx context.Context, arg DeletePoolParams) error {
	_, err := q.db.Exec(ctx, deletePool, arg.ChainID, arg.PoolID)
	return err
}

const deleteRound = `-- name: DeleteRound :exec
DELETE FROM rounds
WHERE chain_id = $1
  AND pool_id = $2
  AND round_id = $3
`

type DeleteRoundParams struct {
	ChainID int64 `json:"chain_id"`
	PoolID  int64 `json:"pool_id"`
	RoundID int64 `json:"round_id"`
}

func (q *Queries) DeleteRound(ctx context.Context, arg DeleteRoundParams) error {
	_, err := q.db.Exec(ctx, deleteRound, arg.ChainID, arg.PoolID, arg.RoundID)
	return err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets
WHERE chain_id = $1
  AND ticket_id = $2
`

type DeleteTicketParams struct {
	ChainID  int64 `json:"chain_id"`
	TicketID int64 `json:"ticket_id"`
}

func (q *Queries) DeleteTicket(ctx context.Context, arg DeleteTicketParams) error {
	_, err := q.db.Exec(ctx, deleteTicket, arg.ChainID, arg.TicketID)
	return err
}

const getPool = `-- name: GetPool :one
SELECT id, chain_id, pool_id, creator, protocol_owned, mode, status, paused, close_requested, vrf_pending, initialized, theme_id, ticket_price, total_tickets_per_round, total_prize_budget, pool_instance_group_size, fee_bps, target_rtp_bps, hit_rate_bps, max_prize, selectable, current_round, locked_bond, reserved_prize_budget, locked_next_round_budget, realized_revenue, settled_prize_cost, settled_protocol_cost, accrued_platform_fee, creator_profit_claimed, claimable_creator_profit, created_block, created_tx_hash, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
FROM pools
WHERE chain_id = $1
  AND pool_id = $2
`

type GetPoolParams struct {
	ChainID int64 `json:"chain_id"`
	PoolID  int64 `json:"pool_id"`
}

func (q *Queries) GetPool(ctx context.Context, arg GetPoolParams) (Pool, error) {
	row := q.db.QueryRow(ctx, getPool, arg.ChainID, arg.PoolID)
	var i Pool
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.PoolID,
		&i.Creator,
		&i.ProtocolOwned,
		&i.Mode,
		&i.Status,
		&i.Paused,
		&i.CloseRequested,
		&i.VrfPending,
		&i.Initialized,
		&i.ThemeID,
		&i.TicketPrice,
		&i.TotalTicketsPerRound,
		&i.TotalPrizeBudget,
		&i.PoolInstanceGroupSize,
		&i.FeeBps,
		&i.TargetRtpBps,
		&i.HitRateBps,
		&i.MaxPrize,
		&i.Selectable,
		&i.CurrentRound,
		&i.LockedBond,
		&i.ReservedPrizeBudget,
		&i.LockedNextRoundBudget,
		&i.RealizedRevenue,
		&i.SettledPrizeCost,
		&i.SettledProtocolCost,
		&i.AccruedPlatformFee,
		&i.CreatorProfitClaimed,
		&i.ClaimableCreatorProfit,
		&i.CreatedBlock,
		&i.CreatedTxHash,
		&i.LastEventBlock,
		&i.LastEventTxHash,
		&i.LastEventLogIndex,
		&i.LastEventBlockHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRound = `-- name: GetRound :one
SELECT id, chain_id, pool_id, round_id, status, sold_count, scratched_count, claimed_count, win_claimable_count, total_tickets, ticket_price, round_prize_budget, vrf_request_ref, shuffle_root, last_vrf_requested_at, last_vrf_initialized_at, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
FROM rounds
WHERE chain_id = $1
  AND pool_id = $2
  AND round_id = $3
`

type GetRoundParams struct {
	ChainID int64 `json:"chain_id"`
	PoolID  int64 `json:"pool_id"`
	RoundID int64 `json:"round_id"`
}

func (q *Queries) GetRound(ctx context.Context, arg GetRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, getRound, arg.ChainID, arg.PoolID, arg.RoundID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.PoolID,
		&i.RoundID,
		&i.Status,
		&i.SoldCount,
		&i.ScratchedCount,
		&i.ClaimedCount,
		&i.WinClaimableCount,
		&i.TotalTickets,
		&i.TicketPrice,
		&i.RoundPrizeBudget,
		&i.VrfRequestRef,
		&i.ShuffleRoot,
		&i.LastVrfRequestedAt,
		&i.LastVrfInitializedAt,
		&i.LastEventBlock,
		&i.LastEventTxHash,
		&i.LastEventLogIndex,
		&i.LastEventBlockHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, chain_id, ticket_id, pool_id, round_id, owner, ticket_index, status, reveal_authorized, transferred_before_scratch, mint_tx_hash, claimed_by, claim_clear_reward_amount, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
FROM tickets
WHERE chain_id = $1
  AND ticket_id = $2
`

type GetTicketParams struct {
	ChainID  int64 `json:"chain_id"`
	TicketID int64 `json:"ticket_id"`
}

func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, arg.ChainID, arg.TicketID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.TicketID,
		&i.PoolID,
		&i.RoundID,
		&i.Owner,
		&i.TicketIndex,
		&i.Status,
		&i.RevealAuthorized,
		&i.TransferredBeforeScratch,
		&i.MintTxHash,
		&i.ClaimedBy,
		&i.ClaimClearRewardAmount,
		&i.LastEventBlock,
		&i.LastEventTxHash,
		&i.LastEventLogIndex,
		&i.LastEventBlockHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPools = `-- name: ListPools :many
SELECT id, chain_id, pool_id, creator, protocol_owned, mode, status, paused, close_requested, vrf_pending, initialized, theme_id, ticket_price, total_tickets_per_round, total_prize_budget, pool_instance_group_size, fee_bps, target_rtp_bps, hit_rate_bps, max_prize, selectable, current_round, locked_bond, reserved_prize_budget, locked_next_round_budget, realized_revenue, settled_prize_cost, settled_protocol_cost, accrued_platform_fee, creator_profit_claimed, claimable_creator_profit, created_block, created_tx_hash, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
FROM pools
WHERE chain_id = $1
ORDER BY pool_id DESC
LIMIT $2 OFFSET $3
`

type ListPoolsParams struct {
	ChainID int64 `json:"chain_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPools(ctx context.Context, arg ListPoolsParams) ([]Pool, error) {
	rows, err := q.db.Query(ctx, listPools, arg.ChainID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pool{}
	for rows.Next() {
		var i Pool
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.PoolID,
			&i.Creator,
			&i.ProtocolOwned,
			&i.Mode,
			&i.Status,
			&i.Paused,
			&i.CloseRequested,
			&i.VrfPending,
			&i.Initialized,
			&i.ThemeID,
			&i.TicketPrice,
			&i.TotalTicketsPerRound,
			&i.TotalPrizeBudget,
			&i.PoolInstanceGroupSize,
			&i.FeeBps,
			&i.TargetRtpBps,
			&i.HitRateBps,
			&i.MaxPrize,
			&i.Selectable,
			&i.CurrentRound,
			&i.LockedBond,
			&i.ReservedPrizeBudget,
			&i.LockedNextRoundBudget,
			&i.RealizedRevenue,
			&i.SettledPrizeCost,
			&i.SettledProtocolCost,
			&i.AccruedPlatformFee,
			&i.CreatorProfitClaimed,
			&i.ClaimableCreatorProfit,
			&i.CreatedBlock,
			&i.CreatedTxHash,
			&i.LastEventBlock,
			&i.LastEventTxHash,
			&i.LastEventLogIndex,
			&i.LastEventBlockHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByOwner = `-- name: ListTicketsByOwner :many
SELECT id, chain_id, ticket_id, pool_id, round_id, owner, ticket_index, status, reveal_authorized, transferred_before_scratch, mint_tx_hash, claimed_by, claim_clear_reward_amount, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
FROM tickets
WHERE chain_id = $1
  AND lower(owner) = lower($2)
ORDER BY ticket_id DESC
LIMIT $3 OFFSET $4
`

type ListTicketsByOwnerParams struct {
	ChainID int64  `json:"chain_id"`
	Lower   string `json:"lower"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListTicketsByOwner(ctx context.Context, arg ListTicketsByOwnerParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByOwner,
		arg.ChainID,
		arg.Lower,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.TicketID,
			&i.PoolID,
			&i.RoundID,
			&i.Owner,
			&i.TicketIndex,
			&i.Status,
			&i.RevealAuthorized,
			&i.TransferredBeforeScratch,
			&i.MintTxHash,
			&i.ClaimedBy,
			&i.ClaimClearRewardAmount,
			&i.LastEventBlock,
			&i.LastEventTxHash,
			&i.LastEventLogIndex,
			&i.LastEventBlockHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWinsByUser = `-- name: ListWinsByUser :many
SELECT id, chain_id, ticket_id, pool_id, round_id, owner, ticket_index, status, reveal_authorized, transferred_before_scratch, mint_tx_hash, claimed_by, claim_clear_reward_amount, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
FROM tickets
WHERE chain_id = $1
  AND lower(claimed_by) = lower($2)
  AND claim_clear_reward_amount > 0
ORDER BY ticket_id DESC
LIMIT $3 OFFSET $4
`

type ListWinsByUserParams struct {
	ChainID int64  `json:"chain_id"`
	Lower   string `json:"lower"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListWinsByUser(ctx context.Context, arg ListWinsByUserParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listWinsByUser,
		arg.ChainID,
		arg.Lower,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.TicketID,
			&i.PoolID,
			&i.RoundID,
			&i.Owner,
			&i.TicketIndex,
			&i.Status,
			&i.RevealAuthorized,
			&i.TransferredBeforeScratch,
			&i.MintTxHash,
			&i.ClaimedBy,
			&i.ClaimClearRewardAmount,
			&i.LastEventBlock,
			&i.LastEventTxHash,
			&i.LastEventLogIndex,
			&i.LastEventBlockHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPool = `-- name: UpsertPool :one
INSERT INTO pools (
    chain_id,
    pool_id,
    creator,
    protocol_owned,
    mode,
    status,
    paused,
    close_requested,
    vrf_pending,
    initialized,
    theme_id,
    ticket_price,
    total_tickets_per_round,
    total_prize_budget,
    pool_instance_group_size,
    fee_bps,
    target_rtp_bps,
    hit_rate_bps,
    max_prize,
    selectable,
    current_round,
    locked_bond,
    reserved_prize_budget,
    locked_next_round_budget,
    realized_revenue,
    settled_prize_cost,
    settled_protocol_cost,
    accrued_platform_fee,
    creator_profit_claimed,
    claimable_creator_profit,
    created_block,
    created_tx_hash,
    last_event_block,
    last_event_tx_hash,
    last_event_log_index,
    last_event_block_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36
)
ON CONFLICT (chain_id, pool_id) DO UPDATE SET
    creator = EXCLUDED.creator,
    protocol_owned = EXCLUDED.protocol_owned,
    mode = EXCLUDED.mode,
    status = EXCLUDED.status,
    paused = EXCLUDED.paused,
    close_requested = EXCLUDED.close_requested,
    vrf_pending = EXCLUDED.vrf_pending,
    initialized = EXCLUDED.initialized,
    theme_id = EXCLUDED.theme_id,
    ticket_price = EXCLUDED.ticket_price,
    total_tickets_per_round = EXCLUDED.total_tickets_per_round,
    total_prize_budget = EXCLUDED.total_prize_budget,
    pool_instance_group_size = EXCLUDED.pool_instance_group_size,
    fee_bps = EXCLUDED.fee_bps,
    target_rtp_bps = EXCLUDED.target_rtp_bps,
    hit_rate_bps = EXCLUDED.hit_rate_bps,
    max_prize = EXCLUDED.max_prize,
    selectable = EXCLUDED.selectable,
    current_round = EXCLUDED.current_round,
    locked_bond = EXCLUDED.locked_bond,
    reserved_prize_budget = EXCLUDED.reserved_prize_budget,
    locked_next_round_budget = EXCLUDED.locked_next_round_budget,
    realized_revenue = EXCLUDED.realized_revenue,
    settled_prize_cost = EXCLUDED.settled_prize_cost,
    settled_protocol_cost = EXCLUDED.settled_protocol_cost,
    accrued_platform_fee = EXCLUDED.accrued_platform_fee,
    creator_profit_claimed = EXCLUDED.creator_profit_claimed,
    claimable_creator_profit = EXCLUDED.claimable_creator_profit,
    created_block = EXCLUDED.created_block,
    created_tx_hash = EXCLUDED.created_tx_hash,
    last_event_block = EXCLUDED.last_event_block,
    last_event_tx_hash = EXCLUDED.last_event_tx_hash,
    last_event_log_index = EXCLUDED.last_event_log_index,
    last_event_block_hash = EXCLUDED.last_event_block_hash,
    updated_at = NOW()
RETURNING id, chain_id, pool_id, creator, protocol_owned, mode, status, paused, close_requested, vrf_pending, initialized, theme_id, ticket_price, total_tickets_per_round, total_prize_budget, pool_instance_group_size, fee_bps, target_rtp_bps, hit_rate_bps, max_prize, selectable, current_round, locked_bond, reserved_prize_budget, locked_next_round_budget, realized_revenue, settled_prize_cost, settled_protocol_cost, accrued_platform_fee, creator_profit_claimed, claimable_creator_profit, created_block, created_tx_hash, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
`

type UpsertPoolParams struct {
	ChainID                int64  `json:"chain_id"`
	PoolID                 int64  `json:"pool_id"`
	Creator                string `json:"creator"`
	ProtocolOwned          bool   `json:"protocol_owned"`
	Mode                   string `json:"mode"`
	Status                 string `json:"status"`
	Paused                 bool   `json:"paused"`
	CloseRequested         bool   `json:"close_requested"`
	VrfPending             bool   `json:"vrf_pending"`
	Initialized            bool   `json:"initialized"`
	ThemeID                string `json:"theme_id"`
	TicketPrice            int64  `json:"ticket_price"`
	TotalTicketsPerRound   int64  `json:"total_tickets_per_round"`
	TotalPrizeBudget       int64  `json:"total_prize_budget"`
	PoolInstanceGroupSize  int64  `json:"pool_instance_group_size"`
	FeeBps                 int32  `json:"fee_bps"`
	TargetRtpBps           int32  `json:"target_rtp_bps"`
	HitRateBps             int32  `json:"hit_rate_bps"`
	MaxPrize               int64  `json:"max_prize"`
	Selectable             bool   `json:"selectable"`
	CurrentRound           int64  `json:"current_round"`
	LockedBond             int64  `json:"locked_bond"`
	ReservedPrizeBudget    int64  `json:"reserved_prize_budget"`
	LockedNextRoundBudget  int64  `json:"locked_next_round_budget"`
	RealizedRevenue        int64  `json:"realized_revenue"`
	SettledPrizeCost       int64  `json:"settled_prize_cost"`
	SettledProtocolCost    int64  `json:"settled_protocol_cost"`
	AccruedPlatformFee     int64  `json:"accrued_platform_fee"`
	CreatorProfitClaimed   int64  `json:"creator_profit_claimed"`
	ClaimableCreatorProfit int64  `json:"claimable_creator_profit"`
	CreatedBlock           int64  `json:"created_block"`
	CreatedTxHash          string `json:"created_tx_hash"`
	LastEventBlock         int64  `json:"last_event_block"`
	LastEventTxHash        string `json:"last_event_tx_hash"`
	LastEventLogIndex      int64  `json:"last_event_log_index"`
	LastEventBlockHash     string `json:"last_event_block_hash"`
}

func (q *Queries) UpsertPool(ctx context.Context, arg UpsertPoolParams) (Pool, error) {
	row := q.db.QueryRow(ctx, upsertPool,
		arg.ChainID,
		arg.PoolID,
		arg.Creator,
		arg.ProtocolOwned,
		arg.Mode,
		arg.Status,
		arg.Paused,
		arg.CloseRequested,
		arg.VrfPending,
		arg.Initialized,
		arg.ThemeID,
		arg.TicketPrice,
		arg.TotalTicketsPerRound,
		arg.TotalPrizeBudget,
		arg.PoolInstanceGroupSize,
		arg.FeeBps,
		arg.TargetRtpBps,
		arg.HitRateBps,
		arg.MaxPrize,
		arg.Selectable,
		arg.CurrentRound,
		arg.LockedBond,
		arg.ReservedPrizeBudget,
		arg.LockedNextRoundBudget,
		arg.RealizedRevenue,
		arg.SettledPrizeCost,
		arg.SettledProtocolCost,
		arg.AccruedPlatformFee,
		arg.CreatorProfitClaimed,
		arg.ClaimableCreatorProfit,
		arg.CreatedBlock,
		arg.CreatedTxHash,
		arg.LastEventBlock,
		arg.LastEventTxHash,
		arg.LastEventLogIndex,
		arg.LastEventBlockHash,
	)
	var i Pool
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.PoolID,
		&i.Creator,
		&i.ProtocolOwned,
		&i.Mode,
		&i.Status,
		&i.Paused,
		&i.CloseRequested,
		&i.VrfPending,
		&i.Initialized,
		&i.ThemeID,
		&i.TicketPrice,
		&i.TotalTicketsPerRound,
		&i.TotalPrizeBudget,
		&i.PoolInstanceGroupSize,
		&i.FeeBps,
		&i.TargetRtpBps,
		&i.HitRateBps,
		&i.MaxPrize,
		&i.Selectable,
		&i.CurrentRound,
		&i.LockedBond,
		&i.ReservedPrizeBudget,
		&i.LockedNextRoundBudget,
		&i.RealizedRevenue,
		&i.SettledPrizeCost,
		&i.SettledProtocolCost,
		&i.AccruedPlatformFee,
		&i.CreatorProfitClaimed,
		&i.ClaimableCreatorProfit,
		&i.CreatedBlock,
		&i.CreatedTxHash,
		&i.LastEventBlock,
		&i.LastEventTxHash,
		&i.LastEventLogIndex,
		&i.LastEventBlockHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRound = `-- name: UpsertRound :one
INSERT INTO rounds (
    chain_id,
    pool_id,
    round_id,
    status,
    sold_count,
    scratched_count,
    claimed_count,
    win_claimable_count,
    total_tickets,
    ticket_price,
    round_prize_budget,
    vrf_request_ref,
    shuffle_root,
    last_vrf_requested_at,
    last_vrf_initialized_at,
    last_event_block,
    last_event_tx_hash,
    last_event_log_index,
    last_event_block_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (chain_id, pool_id, round_id) DO UPDATE SET
    status = EXCLUDED.status,
    sold_count = EXCLUDED.sold_count,
    scratched_count = EXCLUDED.scratched_count,
    claimed_count = EXCLUDED.claimed_count,
    win_claimable_count = EXCLUDED.win_claimable_count,
    total_tickets = EXCLUDED.total_tickets,
    ticket_price = EXCLUDED.ticket_price,
    round_prize_budget = EXCLUDED.round_prize_budget,
    vrf_request_ref = EXCLUDED.vrf_request_ref,
    shuffle_root = EXCLUDED.shuffle_root,
    last_vrf_requested_at = EXCLUDED.last_vrf_requested_at,
    last_vrf_initialized_at = EXCLUDED.last_vrf_initialized_at,
    last_event_block = EXCLUDED.last_event_block,
    last_event_tx_hash = EXCLUDED.last_event_tx_hash,
    last_event_log_index = EXCLUDED.last_event_log_index,
    last_event_block_hash = EXCLUDED.last_event_block_hash,
    updated_at = NOW()
RETURNING id, chain_id, pool_id, round_id, status, sold_count, scratched_count, claimed_count, win_claimable_count, total_tickets, ticket_price, round_prize_budget, vrf_request_ref, shuffle_root, last_vrf_requested_at, last_vrf_initialized_at, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
`

type UpsertRoundParams struct {
	ChainID              int64              `json:"chain_id"`
	PoolID               int64              `json:"pool_id"`
	RoundID              int64              `json:"round_id"`
	Status               string             `json:"status"`
	SoldCount            int64              `json:"sold_count"`
	ScratchedCount       int64              `json:"scratched_count"`
	ClaimedCount         int64              `json:"claimed_count"`
	WinClaimableCount    int64              `json:"win_claimable_count"`
	TotalTickets         int64              `json:"total_tickets"`
	TicketPrice          int64              `json:"ticket_price"`
	RoundPrizeBudget     int64              `json:"round_prize_budget"`
	VrfRequestRef        string             `json:"vrf_request_ref"`
	ShuffleRoot          string             `json:"shuffle_root"`
	LastVrfRequestedAt   pgtype.Timestamptz `json:"last_vrf_requested_at"`
	LastVrfInitializedAt pgtype.Timestamptz `json:"last_vrf_initialized_at"`
	LastEventBlock       int64              `json:"last_event_block"`
	LastEventTxHash      string             `json:"last_event_tx_hash"`
	LastEventLogIndex    int64              `json:"last_event_log_index"`
	LastEventBlockHash   string             `json:"last_event_block_hash"`
}

func (q *Queries) UpsertRound(ctx context.Context, arg UpsertRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, upsertRound,
		arg.ChainID,
		arg.PoolID,
		arg.RoundID,
		arg.Status,
		arg.SoldCount,
		arg.ScratchedCount,
		arg.ClaimedCount,
		arg.WinClaimableCount,
		arg.TotalTickets,
		arg.TicketPrice,
		arg.RoundPrizeBudget,
		arg.VrfRequestRef,
		arg.ShuffleRoot,
		arg.LastVrfRequestedAt,
		arg.LastVrfInitializedAt,
		arg.LastEventBlock,
		arg.LastEventTxHash,
		arg.LastEventLogIndex,
		arg.LastEventBlockHash,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.PoolID,
		&i.RoundID,
		&i.Status,
		&i.SoldCount,
		&i.ScratchedCount,
		&i.ClaimedCount,
		&i.WinClaimableCount,
		&i.TotalTickets,
		&i.TicketPrice,
		&i.RoundPrizeBudget,
		&i.VrfRequestRef,
		&i.ShuffleRoot,
		&i.LastVrfRequestedAt,
		&i.LastVrfInitializedAt,
		&i.LastEventBlock,
		&i.LastEventTxHash,
		&i.LastEventLogIndex,
		&i.LastEventBlockHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTicket = `-- name: UpsertTicket :one
INSERT INTO tickets (
    chain_id,
    ticket_id,
    pool_id,
    round_id,
    owner,
    ticket_index,
    status,
    reveal_authorized,
    transferred_before_scratch,
    mint_tx_hash,
    claimed_by,
    claim_clear_reward_amount,
    last_event_block,
    last_event_tx_hash,
    last_event_log_index,
    last_event_block_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (chain_id, ticket_id) DO UPDATE SET
    pool_id = EXCLUDED.pool_id,
    round_id = EXCLUDED.round_id,
    owner = EXCLUDED.owner,
    ticket_index = EXCLUDED.ticket_index,
    status = EXCLUDED.status,
    reveal_authorized = EXCLUDED.reveal_authorized,
    transferred_before_scratch = EXCLUDED.transferred_before_scratch,
    mint_tx_hash = EXCLUDED.mint_tx_hash,
    claimed_by = EXCLUDED.claimed_by,
    claim_clear_reward_amount = EXCLUDED.claim_clear_reward_amount,
    last_event_block = EXCLUDED.last_event_block,
    last_event_tx_hash = EXCLUDED.last_event_tx_hash,
    last_event_log_index = EXCLUDED.last_event_log_index,
    last_event_block_hash = EXCLUDED.last_event_block_hash,
    updated_at = NOW()
RETURNING id, chain_id, ticket_id, pool_id, round_id, owner, ticket_index, status, reveal_authorized, transferred_before_scratch, mint_tx_hash, claimed_by, claim_clear_reward_amount, last_event_block, last_event_tx_hash, last_event_log_index, last_event_block_hash, created_at, updated_at
`

type UpsertTicketParams struct {
	ChainID                  int64  `json:"chain_id"`
	TicketID                 int64  `json:"ticket_id"`
	PoolID                   int64  `json:"pool_id"`
	RoundID                  int64  `json:"round_id"`
	Owner                    string `json:"owner"`
	TicketIndex              int64  `json:"ticket_index"`
	Status                   string `json:"status"`
	RevealAuthorized         bool   `json:"reveal_authorized"`
	TransferredBeforeScratch bool   `json:"transferred_before_scratch"`
	MintTxHash               string `json:"mint_tx_hash"`
	ClaimedBy                string `json:"claimed_by"`
	ClaimClearRewardAmount   int64  `json:"claim_clear_reward_amount"`
	LastEventBlock           int64  `json:"last_event_block"`
	LastEventTxHash          string `json:"last_event_tx_hash"`
	LastEventLogIndex        int64  `json:"last_event_log_index"`
	LastEventBlockHash       string `json:"last_event_block_hash"`
}

func (q *Queries) UpsertTicket(ctx context.Context, arg UpsertTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, upsertTicket,
		arg.ChainID,
		arg.TicketID,
		arg.PoolID,
		arg.RoundID,
		arg.Owner,
		arg.TicketIndex,
		arg.Status,
		arg.RevealAuthorized,
		arg.TransferredBeforeScratch,
		arg.MintTxHash,
		arg.ClaimedBy,
		arg.ClaimClearRewardAmount,
		arg.LastEventBlock,
		arg.LastEventTxHash,
		arg.LastEventLogIndex,
		arg.LastEventBlockHash,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.TicketID,
		&i.PoolID,
		&i.RoundID,
		&i.Owner,
		&i.TicketIndex,
		&i.Status,
		&i.RevealAuthorized,
		&i.TransferredBeforeScratch,
		&i.MintTxHash,
		&i.ClaimedBy,
		&i.ClaimClearRewardAmount,
		&i.LastEventBlock,
		&i.LastEventTxHash,
		&i.LastEventLogIndex,
		&i.LastEventBlockHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    wallet_address,
    last_seen_at
) VALUES (
    $1, NOW()
)
ON CONFLICT (wallet_address) DO UPDATE SET
    last_seen_at = NOW()
RETURNING id, wallet_address, created_at, last_seen_at
`

func (q *Queries) UpsertUser(ctx context.Context, walletAddress string) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, walletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
