// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	BackfillGaslessRequestOnchainState(ctx context.Context, arg BackfillGaslessRequestOnchainStateParams) (GaslessRequest, error)
	ClaimDueJobs(ctx context.Context, arg ClaimDueJobsParams) ([]Job, error)
	CountRecentGaslessRequestsByUser(ctx context.Context, arg CountRecentGaslessRequestsByUserParams) (int64, error)
	DeleteIndexedLogsFromBlock(ctx context.Context, arg DeleteIndexedLogsFromBlockParams) error
	DeletePool(ctx context.Context, arg DeletePoolParams) error
	DeleteRound(ctx context.Context, arg DeleteRoundParams) error
	DeleteTicket(ctx context.Context, arg DeleteTicketParams) error
	GetActiveDeployment(ctx context.Context, arg GetActiveDeploymentParams) (DeploymentRegistry, error)
	GetActiveGaslessControl(ctx context.Context, arg GetActiveGaslessControlParams) (GaslessControl, error)
	GetGaslessRequestByDigest(ctx context.Context, digest string) (GaslessRequest, error)
	GetGlobalCostTotal(ctx context.Context, chainID int64) (int64, error)
	GetGlobalSponsorCostTotal(ctx context.Context, chainID int64) (int64, error)
	GetIndexerCursor(ctx context.Context, arg GetIndexerCursorParams) (IndexerCursor, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	GetLatestRevealRequest(ctx context.Context, arg GetLatestRevealRequestParams) (RevealRequest, error)
	GetPool(ctx context.Context, arg GetPoolParams) (Pool, error)
	GetPoolCostTotal(ctx context.Context, arg GetPoolCostTotalParams) (int64, error)
	GetPoolCostTotals(ctx context.Context, arg GetPoolCostTotalsParams) ([]GetPoolCostTotalsRow, error)
	GetPoolSponsorCostTotal(ctx context.Context, arg GetPoolSponsorCostTotalParams) (int64, error)
	GetRevealRequestByJobRef(ctx context.Context, arg GetRevealRequestByJobRefParams) (RevealRequest, error)
	GetRevealRequestByZamaRequestRef(ctx context.Context, arg GetRevealRequestByZamaRequestRefParams) (RevealRequest, error)
	GetRound(ctx context.Context, arg GetRoundParams) (Round, error)
	GetTicket(ctx context.Context, arg GetTicketParams) (Ticket, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertGaslessRequest(ctx context.Context, arg InsertGaslessRequestParams) (GaslessRequest, error)
	InsertIndexedLog(ctx context.Context, arg InsertIndexedLogParams) (IndexedLog, error)
	InsertPoolCostLedger(ctx context.Context, arg InsertPoolCostLedgerParams) (PoolCostLedger, error)
	InsertRevealRequest(ctx context.Context, arg InsertRevealRequestParams) (RevealRequest, error)
	ListActiveDeployments(ctx context.Context, chainID int64) ([]DeploymentRegistry, error)
	ListGaslessRequestsByStatuses(ctx context.Context, arg ListGaslessRequestsByStatusesParams) ([]GaslessRequest, error)
	ListIndexedLogsFromBlock(ctx context.Context, arg ListIndexedLogsFromBlockParams) ([]IndexedLog, error)
	ListJobs(ctx context.Context) ([]Job, error)
	ListPoolCostLedgers(ctx context.Context, arg ListPoolCostLedgersParams) ([]PoolCostLedger, error)
	ListPools(ctx context.Context, arg ListPoolsParams) ([]Pool, error)
	ListStaleSubmittingRevealRequests(ctx context.Context, arg ListStaleSubmittingRevealRequestsParams) ([]RevealRequest, error)
	ListSubmittedRevealRequests(ctx context.Context, arg ListSubmittedRevealRequestsParams) ([]RevealRequest, error)
	ListTicketsByOwner(ctx context.Context, arg ListTicketsByOwnerParams) ([]Ticket, error)
	ListWinsByUser(ctx context.Context, arg ListWinsByUserParams) ([]Ticket, error)
	MarkGaslessRequestResult(ctx context.Context, arg MarkGaslessRequestResultParams) (GaslessRequest, error)
	MarkGaslessRequestSubmitted(ctx context.Context, arg MarkGaslessRequestSubmittedParams) (GaslessRequest, error)
	MarkGaslessRequestValidated(ctx context.Context, digest string) (GaslessRequest, error)
	MarkJobCompleted(ctx context.Context, arg MarkJobCompletedParams) (Job, error)
	MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (Job, error)
	ReleaseStaleRunningJobs(ctx context.Context, dollar_1 int64) ([]Job, error)
	RetryJob(ctx context.Context, id int64) (Job, error)
	UpdateRevealRequestProxyState(ctx context.Context, arg UpdateRevealRequestProxyStateParams) (RevealRequest, error)
	UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) (DeploymentRegistry, error)
	UpsertGaslessControl(ctx context.Context, arg UpsertGaslessControlParams) (GaslessControl, error)
	UpsertIndexerCursor(ctx context.Context, arg UpsertIndexerCursorParams) (IndexerCursor, error)
	UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error)
	UpsertPool(ctx context.Context, arg UpsertPoolParams) (Pool, error)
	UpsertRound(ctx context.Context, arg UpsertRoundParams) (Round, error)
	UpsertTicket(ctx context.Context, arg UpsertTicketParams) (Ticket, error)
	UpsertUser(ctx context.Context, walletAddress string) (User, error)
}

var _ Querier = (*Queries)(nil)
