// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reveal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestRevealRequest = `-- name: GetLatestRevealRequest :one
SELECT id, chain_id, ticket_id, request_user, owner_snapshot, request_status, zama_request_ref, ticket_status_snapshot, reveal_authorized_snapshot, auth_payload, claim_clear_reward_amount, claim_proof_ref, expires_at, created_at, updated_at
FROM reveal_requests
WHERE chain_id = $1
  AND ticket_id = $2
  AND lower(request_user) = lower($3)
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestRevealRequestParams struct {
	ChainID  int64  `json:"chain_id"`
	TicketID int64  `json:"ticket_id"`
	Lower    string `json:"lower"`
}

func (q *Queries) GetLatestRevealRequest(ctx context.Context, arg GetLatestRevealRequestParams) (RevealRequest, error) {
	row := q.db.QueryRow(ctx, getLatestRevealRequest, arg.ChainID, arg.TicketID, arg.Lower)
	var i RevealRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.TicketID,
		&i.RequestUser,
		&i.OwnerSnapshot,
		&i.RequestStatus,
		&i.ZamaRequestRef,
		&i.TicketStatusSnapshot,
		&i.RevealAuthorizedSnapshot,
		&i.AuthPayload,
		&i.ClaimClearRewardAmount,
		&i.ClaimProofRef,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRevealRequestByJobRef = `-- name: GetRevealRequestByJobRef :one
SELECT id, chain_id, ticket_id, request_user, owner_snapshot, request_status, zama_request_ref, ticket_status_snapshot, reveal_authorized_snapshot, auth_payload, claim_clear_reward_amount, claim_proof_ref, expires_at, created_at, updated_at
FROM reveal_requests
WHERE chain_id = $1
  AND ticket_id = $2
  AND claim_proof_ref = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetRevealRequestByJobRefParams struct {
	ChainID       int64  `json:"chain_id"`
	TicketID      int64  `json:"ticket_id"`
	ClaimProofRef string `json:"claim_proof_ref"`
}

func (q *Queries) GetRevealRequestByJobRef(ctx context.Context, arg GetRevealRequestByJobRefParams) (RevealRequest, error) {
	row := q.db.QueryRow(ctx, getRevealRequestByJobRef, arg.ChainID, arg.TicketID, arg.ClaimProofRef)
	var i RevealRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.TicketID,
		&i.RequestUser,
		&i.OwnerSnapshot,
		&i.RequestStatus,
		&i.ZamaRequestRef,
		&i.TicketStatusSnapshot,
		&i.RevealAuthorizedSnapshot,
		&i.AuthPayload,
		&i.ClaimClearRewardAmount,
		&i.ClaimProofRef,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRevealRequestByZamaRequestRef = `-- name: GetRevealRequestByZamaRequestRef :one
SELECT id, chain_id, ticket_id, request_user, owner_snapshot, request_status, zama_request_ref, ticket_status_snapshot, reveal_authorized_snapshot, auth_payload, claim_clear_reward_amount, claim_proof_ref, expires_at, created_at, updated_at
FROM reveal_requests
WHERE chain_id = $1
  AND ticket_id = $2
  AND zama_request_ref = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetRevealRequestByZamaRequestRefParams struct {
	ChainID        int64  `json:"chain_id"`
	TicketID       int64  `json:"ticket_id"`
	ZamaRequestRef string `json:"zama_request_ref"`
}

func (q *Queries) GetRevealRequestByZamaRequestRef(ctx context.Context, arg GetRevealRequestByZamaRequestRefParams) (RevealRequest, error) {
	row := q.db.QueryRow(ctx, getRevealRequestByZamaRequestRef, arg.ChainID, arg.TicketID, arg.ZamaRequestRef)
	var i RevealRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.TicketID,
		&i.RequestUser,
		&i.OwnerSnapshot,
		&i.RequestStatus,
		&i.ZamaRequestRef,
		&i.TicketStatusSnapshot,
		&i.RevealAuthorizedSnapshot,
		&i.AuthPayload,
		&i.ClaimClearRewardAmount,
		&i.ClaimProofRef,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRevealRequest = `-- name: InsertRevealRequest :one
INSERT INTO reveal_requests (
    chain_id,
    ticket_id,
    request_user,
    owner_snapshot,
    request_status,
    zama_request_ref,
    ticket_status_snapshot,
    reveal_authorized_snapshot,
    auth_payload,
    claim_clear_reward_amount,
    claim_proof_ref,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, chain_id, ticket_id, request_user, owner_snapshot, request_status, zama_request_ref, ticket_status_snapshot, reveal_authorized_snapshot, auth_payload, claim_clear_reward_amount, claim_proof_ref, expires_at, created_at, updated_at
`

type InsertRevealRequestParams struct {
	ChainID                  int64              `json:"chain_id"`
	TicketID                 int64              `json:"ticket_id"`
	RequestUser              string             `json:"request_user"`
	OwnerSnapshot            string             `json:"owner_snapshot"`
	RequestStatus            string             `json:"request_status"`
	ZamaRequestRef           string             `json:"zama_request_ref"`
	TicketStatusSnapshot     string             `json:"ticket_status_snapshot"`
	RevealAuthorizedSnapshot bool               `json:"reveal_authorized_snapshot"`
	AuthPayload              []byte             `json:"auth_payload"`
	ClaimClearRewardAmount   pgtype.Int8        `json:"claim_clear_reward_amount"`
	ClaimProofRef            string             `json:"claim_proof_ref"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertRevealRequest(ctx context.Context, arg InsertRevealRequestParams) (RevealRequest, error) {
	row := q.db.QueryRow(ctx, insertRevealRequest,
		arg.ChainID,
		arg.TicketID,
		arg.RequestUser,
		arg.OwnerSnapshot,
		arg.RequestStatus,
		arg.ZamaRequestRef,
		arg.TicketStatusSnapshot,
		arg.RevealAuthorizedSnapshot,
		arg.AuthPayload,
		arg.ClaimClearRewardAmount,
		arg.ClaimProofRef,
		arg.ExpiresAt,
	)
	var i RevealRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.TicketID,
		&i.RequestUser,
		&i.OwnerSnapshot,
		&i.RequestStatus,
		&i.ZamaRequestRef,
		&i.TicketStatusSnapshot,
		&i.RevealAuthorizedSnapshot,
		&i.AuthPayload,
		&i.ClaimClearRewardAmount,
		&i.ClaimProofRef,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaleSubmittingRevealRequests = `-- name: ListStaleSubmittingRevealRequests :many
SELECT id, chain_id, ticket_id, request_user, owner_snapshot, request_status, zama_request_ref, ticket_status_snapshot, reveal_authorized_snapshot, auth_payload, claim_clear_reward_amount, claim_proof_ref, expires_at, created_at, updated_at
FROM reveal_requests
WHERE chain_id = $1
  AND request_status = 'submitting'
  AND updated_at <= $2
ORDER BY updated_at ASC
LIMIT $3
`

type ListStaleSubmittingRevealRequestsParams struct {
	ChainID   int64              `json:"chain_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListStaleSubmittingRevealRequests(ctx context.Context, arg ListStaleSubmittingRevealRequestsParams) ([]RevealRequest, error) {
	rows, err := q.db.Query(ctx, listStaleSubmittingRevealRequests, arg.ChainID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevealRequest{}
	for rows.Next() {
		var i RevealRequest
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.TicketID,
			&i.RequestUser,
			&i.OwnerSnapshot,
			&i.RequestStatus,
			&i.ZamaRequestRef,
			&i.TicketStatusSnapshot,
			&i.RevealAuthorizedSnapshot,
			&i.AuthPayload,
			&i.ClaimClearRewardAmount,
			&i.ClaimProofRef,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmittedRevealRequests = `-- name: ListSubmittedRevealRequests :many
SELECT id, chain_id, ticket_id, request_user, owner_snapshot, request_status, zama_request_ref, ticket_status_snapshot, reveal_authorized_snapshot, auth_payload, claim_clear_reward_amount, claim_proof_ref, expires_at, created_at, updated_at
FROM reveal_requests
WHERE chain_id = $1
  AND request_status = 'submitted'
  AND claim_proof_ref <> ''
ORDER BY updated_at ASC
LIMIT $2
`

type ListSubmittedRevealRequestsParams struct {
	ChainID int64 `json:"chain_id"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) ListSubmittedRevealRequests(ctx context.Context, arg ListSubmittedRevealRequestsParams) ([]RevealRequest, error) {
	rows, err := q.db.Query(ctx, listSubmittedRevealRequests, arg.ChainID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevealRequest{}
	for rows.Next() {
		var i RevealRequest
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.TicketID,
			&i.RequestUser,
			&i.OwnerSnapshot,
			&i.RequestStatus,
			&i.ZamaRequestRef,
			&i.TicketStatusSnapshot,
			&i.RevealAuthorizedSnapshot,
			&i.AuthPayload,
			&i.ClaimClearRewardAmount,
			&i.ClaimProofRef,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRevealRequestProxyState = `-- name: UpdateRevealRequestProxyState :one
UPDATE reveal_requests
SET request_status = $1,
    claim_proof_ref = CASE
        WHEN $2 = '' THEN claim_proof_ref
        ELSE $2
    END,
    updated_at = NOW()
WHERE id = $3
RETURNING id, chain_id, ticket_id, request_user, owner_snapshot, request_status, zama_request_ref, ticket_status_snapshot, reveal_authorized_snapshot, auth_payload, claim_clear_reward_amount, claim_proof_ref, expires_at, created_at, updated_at
`

type UpdateRevealRequestProxyStateParams struct {
	RequestStatus string      `json:"request_status"`
	ClaimProofRef interface{} `json:"claim_proof_ref"`
	ID            int64       `json:"id"`
}

func (q *Queries) UpdateRevealRequestProxyState(ctx context.Context, arg UpdateRevealRequestProxyStateParams) (RevealRequest, error) {
	row := q.db.QueryRow(ctx, updateRevealRequestProxyState, arg.RequestStatus, arg.ClaimProofRef, arg.ID)
	var i RevealRequest
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.TicketID,
		&i.RequestUser,
		&i.OwnerSnapshot,
		&i.RequestStatus,
		&i.ZamaRequestRef,
		&i.TicketStatusSnapshot,
		&i.RevealAuthorizedSnapshot,
		&i.AuthPayload,
		&i.ClaimClearRewardAmount,
		&i.ClaimProofRef,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
